### ISSUE TITLE
Replace universal hero skill tree with political party skill trees.

### ISSUE THREAD

**Issue by Tat011** [captaincobbs/ESG-Mod#1071]
it'd make party preference more relevant and it'd make heroes more distinct

**Comment by captaincobbs** [comment]
Just because of the work involved with this, I don't think this will happen. If you are willing to organize an effort to do this then go ahead, but otherwise chances aren't high that anyone will pick it up.

**Comment by Tat011** [comment]
Im be willing to implement this though ill need help designing them, here's a link to where ill be designing them:
https://docs.google.com/spreadsheets/d/1WsPSb-UdBvLyycnA8fHLZDDT57F3LaKq5AWh75u3nF4/edit#gid=0

**Comment by Arpharnator** [comment]
put to url sharing ples

**Comment by captaincobbs** [comment]
Chart out the entire generic skill tree and how it will change between political parties, that will be more clear.
Make it clear what you change vs what stays the same.

**Comment by wakystuf** [comment]
I agree with @captaincobbs on all counts. My thoughts:
1) I am unlikely to code this
2) I would suggest the following if you want to do it:
-Make the T1 governor skill be +2/4 per pop of the resource associated with each party (Food with ecologists, MP for militarist, infl for religious, etc)
-Probably leave the T1 ship skill, as some of the parties (ex: ecologist) are really hard to come up with logical associated mechanics (I know, since we had to do that for the T6 laws already). And it'll be hard to balance when militarists get +X% damage while some poor group gets a shit effect like +1 probe stock
-Leave the T3 Cooldown skill alone
-Probably leave the flak skill alone, for similar reasons to the T1 ship skill
-Replace the approval skill with approval that's linked to the party (lux deposits for pacifist, strats for industrialist, anomalies for ecologist, gas planets for scientists, per hero level for religious, etc)
-Leave the garrison/senator skill alone
-Replace the capstone skill with something unique to each party, which could be very open-ended

**Comment by Eighth-of-Third** [comment]
This would be a massive amount of work, likely present new balancing issues, and the generalist tree is already pretty good and has many necessary effects like the flak skill and the garrison skill. If you're willing to do it, sure, but this is going to be a very low priority for most people.

**Comment by captaincobbs** [comment]
If no one is willing to code this, then I will go ahead and close the issue.
