### ISSUE TITLE
Re-thinking the Vaulters for fun and meaningful interaction

### ISSUE THREAD

**Issue by qualitymustard** [captaincobbs/ESG-Mod#1079]
I’ve been tossing around some ideas for the Vaulters lately. Not only are they weak and boring to play, but they are inexcusably _neutral_ to encounter in game. They don’t have any notable desires or conflicts with the other factions. They just kinda coolin, and it sucks for everyone.

This is despite the fact that Vaulters have a pretty interesting core identity, being defensive space miners who spent their formative years in science bunkers getting chummy with pirates. Much more interesting than the Sophons on the surface. The issue, then, is that this identity isn’t manifesting in a fun play style. Hunkering down in a few easily defensible systems and waiting for a science victory is a snoozefest.

I have two suggestions that would attempt to fix this, in a very early stage of development and balance. 

### 1: Demilitarized Zones
_Vaulters’ systems benefit from increased production when none of the nodes they connect to are colonized._ 

This principle contributes to the Vaulters’ needs to play tall in carefully considered systems, while also requiring them to take up meaningful space on the galactic map. This in turn creates tension when other factions wants to occupy any of their connecting nodes. This tension scales depending on the node connectivity setting, which for the competitive ruleset is high. The resulting contested space creates sorely needed interplay and a reason for the vaulters to flex their defensive muscle.

### 2: Proactive Protectionism
_Life among the hostile empires of Auriga has instilled a pragmatic xenophobia within the Vaulters. Threats to the internal economy are to be dismantled at any cost._

The primary function of this trait would be a more efficient Raze action, with no effect on approval. This is meant to synergize with the Vaulters’ need for empty connecting nodes. This principle also has the potential to synergize with mining behemoths, as they may prove to be an effective way for the Vaulters to get the strategics they desire without needing to colonize in their demilitarized zones. This plays to their mining identity, which I like. 

I hope that this can open a new conversation about how to make the Vaulters fun to play as or against. 

_________________________________________
_________________________________________

Notes (lots of notes): 
I have no functional idea of how difficult it would be to code AI for this. I also don't know how much the ESG community cares about AI competency.

The DMZ creates a clear target for enemy factions, in that conquering one Vaulters system would open up all surrounding systems to colonization as well. This gives opposing players reason to attack an otherwise less attractive defensive powerhouse, and gives the Vaulters additional targets when reconquering or clearing space for a new system. I think this would probably be a good thing.

Important question: Are the vaulters good enough at exploration to make the choice of systems fun? I feel like those should be fun decisions.

Jury’s currently out on what kind of production bonus the DMZ would give. Some combination of FIDSI? Happiness? Resource deposit output from the systems within the DMZ? Some combination of the above?

The improved raze action would give increased meaning to Vaulters heroes’ increases to siege damage and the like. Currently the need to play tall and lack of dictatorship means that most offensive ground battles are unnecessary. Rill Kata with her siege and manpower deployment increase would do a wonderful job of defending the motherland, lol.

Vaulters may need to get a faction-specific buff to their mining behemoth output to cement their mining identity, but I’m not really experienced enough with non-Hissho miners to know.

Would the Vaulters need additional enabling in order to invade systems in their DMZ without needing to declare war? Or would there be enough deterrent to colonising within the DMZ that nobody would attempt it without declaring war on the Vaulters first? Hmmm

If the DMZ is too difficult to code for, perhaps narrowing the focus to razing and strat mining is the way to go. Less interesting interaction, though. 

Thank u for coming to my ted talk

**Comment by captaincobbs** [comment]
Ok, reading through your idea, some thoughts.
1. DMZs
Making it the area adjacent to a Vaulters system is not possible, it would have to be ON the vaulters system. We could perhaps give them empire-wide maluses just for being sieged instead of blockaded, incentivizing them to attack anyone who isn't friendly, but still leaving friendly relations in the picture. This would probably also make the AI play with, since it tends to be very territorial. My thoughts on the maluses: Science and Strategics, make them pretty strong so that the message is clear, but in turn relieve some of the overcolonization malus the vaulters have.

2. Proactive Protectionism
This is a good approach, I like it. It doesn't mesh well with the DMZ anymore, since that can't exist as your originally had intended, but the general concept is fun. Something to consider though, Vaulters generally will have the slowest ships, just because they don't need to have movement points to do anything other than explore. If you can rethink this idea a bit to match the current mechanics, that'd be wonderful, as what you have now is really creative.

3. Some thoughts
I don't think mining probes are something that the Vaulters should incentivize, but I think just sitting there and gathering strategics is boring. A thought we had to diversify what strategics that vaulters would use is to replace the Filter Barges effect with something similar to the Scavenger Capstone, then slightly lower the bonuses provided from material expertise.

I'd like some way to incentivize the Vaulters to go out and do things, rather than just sit there. Just a list of various ideas I have:
- Add a researchable module that allows heroes to make mobile portals
- Make the "FIDSI while within Colonization Threshold" more active, rather than just a passive bonus you get for being a good little boy
- Some type of strategic boosts you could activate? Similar to the Luxury Boosts (in the same nature of Endless Legend) we were considering adding, we could add strategic boosts.

**Comment by stygmaskyzoo** [comment]
i really like this ideas, the portal module is one i love

what if for the strategic boost we do some tweaked system improvements; instead of ppp or xenoind they unlock a version with hyperium and other one with titanium, with different effects, and you can only choose one, same for t2 and 3 buildings-strats

i can also see a mining twist, but maybe not with behemoths, but with mining modules for heroes; maybe vaulters can have very powerfull strat-based support modules (terraforming, mining, scrapping)...

what about them having some kind of stealing enemy tech? not actual techs, but unique modules (like military cravers) or unique buildings (like horatio reward for 1st quest); this can synergize with them being pirates that hunt for tech to reuse in their favour (this will also encourage more offensive but strategic play imo)

**Comment by qualitymustard** [comment]
Thanks for the responses!!
Good to know that the DMZ as I dreamt it up is completely off the table. 

Thinking about interactions from the root of lore identity brings scrapping to mind, since they’re such scavengers. Vaulters being better at science through scrapping and sophons being better at science through eco makes primal sense in my brain, from a lore perspective.
The vaulters have weak fleets, which encourages engagement from enemy fleets looking for the W. On the flip side, vaulter ships are defensive enough to survive an unfavorable engagement while taking out a few enemy ships, and their strength at reinforcing can make the multiple-turn engagement more beneficial than other factions. More scrapping opportunities…
They could have unique scrapping mechanics — potentially even scrapping that gives strategics? 


I actually love love love the idea of using strategics as EL-style boosters. Using them for system development currently feels like a no-brainer, which I generally dislike in 4X. Perhaps could activate them for powerful empire-wide bonuses, but only activate one at a time for a set amount of turns, which would require you to choose your buffs/where you lose your buffs, which is fun! 



A tall empire conceptually could have an easier time making decisions and responding to crises. Maybe staying below the colonization cap could make the influence cost of passing laws significantly lower? 
This might be my own inexperience, but I have a really hard time defending from hacks as the Vaulters compared to wider empires. That could be something to consider here, too.



Some continued brainstorming about proactive protectionism:

-As a way to get strategics
I personally enjoy the idea of vaulter heroes being able to mine uncolonized planets, like Stygma suggested.
Alternatively, the hypothetical vaulter-unique raze action could give them strategics, like a more effective pillage action. I’m afraid this suggestion leans way too hard on the offensive side of warfare, though.

-As a way to extend the reach of their slow ships
Perhaps vaulter hero ships could build portals on empty/razed systems. No idea if this is actually possible, or if it’s only possible to make hero ships a portal in the way that the argosy is a portal.


P.S. The game does check for colonized neighbors when calculating trade effectiveness, is there anything possible there? (I’m guessing not)

**Comment by Tat011** [comment]
while its an interesting idea that fits their lore, making them reliant on scrapping would make them an offensive faction and would make them more like hissho.
The way you make vaulters more fun isn't by changing how they play against others, but by changing how others play around vaulters (aka make other factions want to attack them).

**Comment by stygmaskyzoo** [comment]
i also think that if the only way to have fun with vaulters is liking eco very much, that should also be developed to its full potential;
lets say they get a titanium ppp that gives: +15 sci * planet, +10 inf * fertile, +1 sci * vaulters (not balanced i guess, just an idea)
and then an hyperium ppp that gives: +15 sci * planet, +10 dust * temperate, +1 approval * vaulters
that way you are making vaulters eco not just a copy of other factions but without their interesting systems, like slave managing for cravers or splices  for horatio, but giving them more choices and startegy involved in what to develop next...
also everything that makes vaulters more dependant on strats is good i guess

**Comment by qualitymustard** [comment]
Okay, after a few more playthroughs I’ve settled on these core proposals (that nobody asked for). I’ll try to present them in a relatively coherent fashion, lol.


## - Conservation Sites
*Faced with the possibility of extinction, cultural survival is the highest priority. Conservation initiatives collect, store and guard material heritage in vast libraries at the center of system-wide defensive infrastructure. These great vaults of knowledge attract the finest minds in the galaxy, as well as those who would make off with the treasure themselves…*

In this hypothetical, the Conservation Sites would be a trait that applies to all Vaulter systems from the start. When an opponent wins a ground battle on a system belonging to a faction with the Conservation Sites trait and selects occupy, on top of gaining the system they will also receive an amount of empire science production and a portion of the opposing empire’s strategic resources.

This is pretty clearly about giving other empires a reason to attack Vaulter systems, while giving the vaulters extra skin in the defense game. My idea was to give the conquering empire a chunk of science equivalent to one turn of the vaulters’ science production. I don’t know how balancing around this would work, since as far as I can tell the Vaulters have enough defense to handle this extra attention, but it doesn’t feel fair to give them a strictly negative quirk without letting the conservation sites contribute in some way to their economy. 
Of all the ideas I’ve toyed with for making the Vaulters interesting targets, I like the fact that this one would keep with their ‘vaulting’ schtick. Turtle tall and keep the treasure for yourself, deep within your ~~mountain stronghold~~ system fortress


## - Proactive Protectionism
*Life among the belligerent powers of the endless universe has instilled a pragmatic xenophobia within this culture. Threats to the internal economy are to be dismantled at any cost.*

This trait would give access to an approval penalty-free raze action, but remove access to the Autonomous Administration system improvement.

My reasoning for this is that it’s more fun to mine empty systems than to colonize them late-game for whatever strats pop up there. I prefer my vaulters tall and spindly, with a mean kick. (Like a giraffe??) I’m not suuuuper wild about using behemoths for mining, but even then I prefer behemoth mining to system grabbing for this particular playstyle, to set it apart. Having a hero-specific mining module (like stygma suggested) could do nice by this.
In a cheeky way, I like that this trait claims to be about protectionism and homeland defense, but is actually just blatant self-interest at the cost of people you can step on. *Cough current events cough*

## - Material Expertise
*Dedicated pursuit of the material sciences allows strategic resources to be actuated in niche industries.*

Full disclosure: I don’t think the material expertise trait as it exists in vanilla or ESG is fun, at all. Luxury resource choice in ESG feels like a (strangely?) welcome random yet balanced element to plan around, removing that altogether in favor of cut-and-dry boosts to FIDS is. Eh
Using strategics as EL-style boosters as Captain Cobbs suggested opens up new worlds of fun choices and decision making. Anything could be fair game! Crazy XP boosters on fleets, upkeep decreases, probe stock/vision range, scrapping shenanigans… This would be a fun wall to throw poop at and see what sticks


## - Streamlined Bureaucracy
*A small, manageable constituency makes for easier politicking and faster governmental response.*

This trait would give an empire within its colonisation limit a percentage decrease to initial law cost (not to upkeep). Personally I’d get a kick out of the vaulters holding more frequent elections as well, being a people that faces unexpected setback after unexpected setback and needing to respond situationally every time. Idk, I like it.


(Notice that I’ve tried to write the flavortext empire-neutral, in keeping with the rest of the game and for the people who’d hypothetically play with these for custom empires)

**Comment by Tat011** [comment]
I really like the first one and agree with the third one but the second one seems very niche and the last one is really random and doesnt fit.

**Comment by captaincobbs** [comment]
Sorry, meant to reply a few days ago but I've been pretty busy.

Making Vaulters focused on mining will never happen, for the simple reason that people without the Supremacy DLC would never be able to fully experience the faction. I also personally don't believe it's a good fit for mechanics, we shouldn't make the Vaulters focus on Industrialist mechanics even if it's a way of obtaining more strategics. If anything, I'd prefer scrapping, but I'm sure that's not going to be a popular decision.

About conservation sites, I don't believe most of that is possible sadly. I can't transfer resources between empires, and I'm not sure if it's a great idea to make the Vaulters _that_ fragile. A few potential ideas instead that serve the same purpose:

1. Destroying Vaulter fleets could give a large amount of Science, Dust, Strategics, etc., scaling with CP and military tech stage of the enemy.

2. Vaulters could start with a building called a "Vault", or something similar. It probably wouldn't do anything on its own and would be destroyed upon conquering the system, but would provide anyone razing, occupying, or pillaging the system a juicy cache of strategics and luxuries, separate from the Vaulter pool, since I have no way of transferring resources between factions.

I like the idea of Proactive Protectionism, but I don't see it being super effective to make the gameplay more exciting, your proposal would likely just push the Vaulters out of their comfort zone with little reward. We could potentially allow the Vaulters to create Outposts, similar to how the Hissho do, but these wouldn't be able to be turned into Colonies, and would only serve to give the Vaulters resources. They would be fed either Influence or Dust to continue mining for another few turns.

I agree that Material Expertise in its current form really isn't fun. I'd like to incentivize using both Luxuries and Strategics, and I have an idea on how to do this, and I'm pretty sure this will at least partially solve the problem, so I'll wait until that's in testing before I take any more suggestions seriously.

Not sure how I feel about streamlined bureaucracy, the Vaulters already don't struggle with upkeep and laws much, but I could perhaps see just straight up giving them a new government type, one that allows you to select laws like in Dictatorship, but multiple parties like in Federation, while also giving bonuses while within the colonization threshold.

Going back to your previous comment, making Heroes put portals on Razed/Pillaged systems isn't possible. If anything, I'd prefer to try to find a way to make pirate portals more useful. Trade is its own separate system from everything else, we can't check nearby nodes in any way sadly.

I agree that the Vaulters should get some type of hacking bonus though, I too have found it really hard to defend as them, and as a scientist faction this shouldn't be the case.

**Comment by captaincobbs** [comment]
(Woops)

**Comment by qualitymustard** [comment]
Giving the Vaulters a 'vault' sounds like the simplest and most impactful way to encourage interaction. Resources gained being separate from the Vaulter pool doesn't detract from that, I think. 

From what I can tell, giving the vaulters strat scrapping mechanics would only be unpopular if it shifts them from being a "defensive" faction to an offensive faction. Encouraging opponents to crack the vault, however, gives the Vaulters actual opportunity for defensive interaction (and therefore scrapping), while the particular design of their ships and the loss of their portal advantage beyond their own systems doesn't make large scale offensives against decent players *that* much more viable. On paper this sounds like a win-win to me. Vaulter interaction and resource getting are two complex problems, and these changes seem like elegant solutions. Testing could prove otherwise...


Makes so much sense not to have the vaulters rely on tech from a different DLC. Totally missed it. Killing your design babies is a part of life, and it looks like proactive protectionism joins the trash heap. (unless in the form of a custom faction trait, but that's a lot of work for a very low priority.)

I'm excited to see what comes out of material expertise development! Considering the track record I have a lot of faith here


In all honesty, the addition of the vault and prospect of defensive warfare already sells me on playing as vaulters in the first place. Material Expertise being fun would be a very welcome cherry on top. I don't feel the need to pursue any other changes until those are tested and measured against counterplay. Taking stock, senate mechanics sound a little frivolous on top of what's being suggested. 

Seems like the vaulters' hacking predicament is the last issue with priority. I am beyond under-qualified to think out loud about this, since I spent the majority of my playtime with penumbra turned off and have no knowledge of the hacking system in the game's code. That aside, it's important to note that if the vaulters would become desirable targets they'd have a gaping hole in their defense if anyone can hack their system and trigger stampedes. 

I like where all of this is headed, and it's already making me rethink the vaulters as a faction worth playing. Good stuff!!

**Comment by captaincobbs** [comment]
> From what I can tell, giving the vaulters strat scrapping mechanics would only be unpopular if it shifts them from being a "defensive" faction to an offensive faction

They just general don't like scrapping, but we already have defensive scrapping as a thing.

> Makes so much sense not to have the vaulters rely on tech from a different DLC. Totally missed it. 
 
😆 sorry, it was a good idea though.

> I'm excited to see what comes out of material expertise development!

Oh right crap I should get on that, thanks for reminding me. Expect changes near the end of the month.

**Comment by captaincobbs** [comment]
Update on this, Vaults and Filter Barge changes will be finished soon. Changes to material expertise may be made (and will almost certainly be a nerf if so), otherwise, I think Vaulters will be in a good place with these changes. Though, Vaults may need to be toned down a bit.

**Comment by Kil10naire** [comment]
a very lengthy discussion that still somehow ended up with me having to find the actual changes on my own
