### ISSUE TITLE
Reduce RB quest requirement

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1120]
![image](https://user-images.githubusercontent.com/49691625/162258712-561ec8ec-41de-4356-8eeb-2de6b7dcce8b.png)
from 3 to 2 of each, allows completion on smaller maps without having to takeover the whole map

**Comment by wakystuf** [comment]
This is fine with me; reasonable point. I might suggest making some other part of their quest slightly harder to offset, since I don't think RB need a net buff rn

**Comment by Provolonage** [comment]
i think rbs questline needs a touch up in terms of dead steps and dead rewards but not really any real buffs, playing them feels like avoiding the dead paths and less of choosing rewards you want, id be fine with rewards being nerfed but being more attainable.

**Comment by wakystuf** [comment]
Hmm...perhaps. Let me know more specifically what you had in mind and we can discuss. RB questline is very complex, so will be kind of a pain to mod

**Comment by Provolonage** [comment]
yeah it really is

**Comment by captaincobbs** [comment]
Any update on this?

**Comment by NoProblemWithThisAcc** [comment]
I'm sure I'll have tomatoes thrown at me because "x race doesn't need buffs" but I think all quests should be viable: totally doable prerequisites and actually useful rewards in most circumstances. Having "noob traps" is very poor (vanilla) design. We can always rebalance with things like newly added traits after quests are viable. And it's not too hard to nerf afterward.

Seriously, let's not under estimate the power of [NEW NERF TRAIT] in making races go from strong to totally unplayable for casual players. Even existing traits like -10% industry can be impactful on any race.

**Comment by wakystuf** [comment]
Merged into #1157
