### ISSUE TITLE
Attempt to apply building cost and gamespeed adjustments to terraforming and anomaly reduction

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1163]
Should be doable, though I may give up if it requires a ton of manual effort with a bajillion individual constructibles

**Comment by Provolonage** [comment]
for anoms this sounds great since fixing most mixed anoms costs as much as building graviton and usually gets you 1-2 fidsi or approval per pop so its giga not worth it. For terraforming if its made any cheaper on fast it might be an issue, so I assume its either a normal speed issue or just a consistency thing we want to iron out. Also if the anoms part is a lot of manual stuff make a branch for me and ill change the numbers for you.

**Comment by wakystuf** [comment]
All set. Yeah when I looked into it I couldn't believe how expensive some of the anomaly reductions were (almost 1k indy), so I adjusted them to all be 480 base on Normal, scaling to 240 base on Fast
