### ISSUE TITLE
Manpower Display Glitch + Game won't end issues

### ISSUE THREAD

**Issue by AXEL-M74** [captaincobbs/ESG-Mod#1168]
Hello,

These issues were encountered using the 1.5 ESG mod. I only run a color palette  and a cosmetic mod to make hero ships black.

The first part of the issue is simple, the game displays much more manpower than the system actually has. Here's an image:
![Manpower](https://user-images.githubusercontent.com/105115857/167257644-8e75b378-1ea7-4aed-a873-9e8f42c63014.png)

Now, for the second issue. I had all victory conditions turned on, but for some reason, the game just won't end. However, worth mentioning is that when I was supposed to win the first time, the game crashed without an error box and reloading the turn before the win made this bug appear. 

And no, I didn't continue the game, the score screen with the option just wouldn't appear. Loading a much older save before this bug occurred saved the issue for some reason, but I have the bugged saves stored in case a save file would be needed. It only runs the two cosmetic, non-essential mods, the color palette mod and black hero ships mod and the saves can load without it.

I was in an alliance, I couldn't gift the Endless Techs even with the option turned on.
Conquering the required systems didn't work either.
Then I tried Obelisks. Still nothing. 
![Game End #1](https://user-images.githubusercontent.com/105115857/167257645-dc547e3a-9138-4ddd-9fe0-6df37f3e370b.png)
![Game End #2](https://user-images.githubusercontent.com/105115857/167257647-c3ed2c81-4cf1-48a4-9019-c5d2bd2fb54b.png)
![Game End #3](https://user-images.githubusercontent.com/105115857/167257648-e30e5057-daa8-418a-8a81-a51247f12d26.png)

I don't know what exactly happened here. it's EXTREMELY odd.

**Comment by Mermixer** [comment]
For the first issue i can tell you that the manpower that is being displayed (~26000) is the maximum deployment limit of the defender, aka how much of the manpower that the system has in total can be deployed.
the reason it exists like this is because youd run into issues where youre invading a system where your opponent has maybe 500 manpower that you would easily beat, but since the system itself can only deploy 400 you would need two turns to invade it.

For the second issue my guess would be that you have already won the game and then click 'continue the game' or whatever its called. obv that would only be possible if you are playing in singleplayer, but my guess would be that you have already won an economic victory already.

**Comment by FluffiestPrincess** [comment]
You say "Loading a much older save before this bug occurred saved the issue for some reason" - can you clarify? You reloaded an earlier save, played up until you should be able to win, then what happened? Did the game crash, continue as if you hadn't actually won, or end in victory as normal?

**Comment by ghost** [comment]
The game ended normally when I used the previous save and went for a win. Traded the Endless tech to the alliance member, researched all of mine and the game ended normally.

It only happened because of the crash. However, I found the issue in the meantime, I should have updated. Basically, the game auto-saved and I loaded the most recent auto-save, but as I ended the turn, it auto-saved just as I won and registered it as a "continue playing" before crashing. I loaded the "continue playing" auto-save without thinking twice.

It's more of an user error than a bug per se in this situation. I already cleared the saves since everything got clogged up and my saves were all a mess.

**Comment by FluffiestPrincess** [comment]
@captaincobbs the "game won't end" issue is not an esg bug; it's more likely a base game crash.

IDK about the manpower thing.

**Comment by Arpharnator** [comment]
im closing this
