### ISSUE TITLE
Partial implementation of Better pop opinions into esg

### ISSUE THREAD

**Issue by Tat011** [captaincobbs/ESG-Mod#1187]
I'm mostly interested in the following:
Adding more planets to the minor homesystem pool (for variety's sake since 1 is really lacking)
Fixing weird or duplicate ideologies like Gnashast/Shredelyn/Cravers all having identical ideology or Epystis not being militarist
Maybe also adding a 4th political trait to all pops to make them more interesting (i'd add a 5th too but the ui looks weird with it so that's never gonna happen) though i doubt this last one will happen.

**Comment by captaincobbs** [comment]
Definitely no for a 4th political trait, can you make a list of the opinion changes you'd be implementing?

**Comment by Tat011** [comment]
Making Srheyedin Militarist, militarist to industrialist (or just industrialist), anti ecologist
Mezari: Scientist, Science to industrialist (or just industrialist), anti ecologist
Giving horatio a 3rd trait which could be Anti pacifist, Ecologist to militarist, Religious to ecologist, pacifist to industrialist or something else
Making Epystis Ecologist, Ecologist to militarist, Religious to militarist (that way they don't have the same ideology as niris and have an ideology that actually fits their lore)
Making Amoeba pacifist, anti indutrialist and either ReligiousToPacifist/PacifistToScientist/ScientificToEcologist or something else, i'm not sure (that way they don't have the same ideology as niris)
Making Gnashast militarist, industrialist to militarist, anti pacifist (this would make them identical to tikanan so...)
Tikanan swapping industrialist to militarist with ecologist to militarist
Remnant changing to pacifist, industrialist to pacifist, anti militarist to fit their lore
Making Pulsos Scientist, scientist to industrialist and anti religious to fit their lore (also making them pragmatist rather than temperate)
Making the sisters, religious, religious to militarist, religious to pacifist
Making sowers ecologist, religious Religious to ecologist
Making harmony religious (cuz their quest theey obsess over), Religious to industrialist anti pacifist (this is cuz they hate dust rather than cuz they hate pacifism)

**Comment by captaincobbs** [comment]
None of these really match up with their lore though

**Comment by Tat011** [comment]
??

**Comment by Tat011** [comment]
That was fast do you know all the faction descriptions by memory or something?
youre gonna have to elaborate cuz i dont see how making the faction explicitly refered to as militarist acutally militarist or giving horatio their third trait or making the explicitly pacifist faction pacifist or the explicitly scientist faction scientist are not matching with the lore

**Comment by captaincobbs** [comment]
Epistis: Epistis are not religious or militarist in the slightest. They are not planetary guardians in a military sense, they are planetary guardians in an ecological sense. Their faction quest makes this very clear.
Amoeba: The Amoeba in ES2 are very different from the Amoeba of ES1. They are not pacifists, they are very clearly focused on ecology and learning more about the environment and different races.
Gnashast: Their lore is that they are racist and hate peace, their political traits are Xenophobia and Anti-Pacifist
Tikanan: Tikanan I could see a real argument for changing, they were originally part of a zoo, but escaped and somehow _very_ quickly evolved to have a civilization, no longer just mindless giant ants. I think Aggressive and Militarist makes sense, but Anti-Pacifists doesn't necessarily feel like it fits because they are more than fine to do their own thing and just not kill anyone.
Sheredyn: From what lorefather has said, the Sheredyn are more or less the same in ES2 as they were in ES1, however, they are less independent. Sheredyn Militarist to Industrialist doesn't make sense to me since functionally it's the opposite, they have a lot of mining colonies and such that entirely exist to fuel their military. They don't particularly care either way about the environment, so anti-ecologist makes no sense to me.
Mezari: The mezari were probably the opposite of the first trait you mention, industrialist to science. They didn't care about ecology either, they lived primarily in their space ships.
Pulsos: An argument could be made here that the pulsos are scientists, but it's mentioned that are very independent and love working on their own projects. They still remain curious and open to exploration, but it's mentioned that their major difference from the Harmony (who very much so are scientists) is that they value their independence, yet still value collectivism.
Sisters of Mercy: They are mentioned at first as being anti-scientist, but through the events of the vaulter prologue come to terms with science. They try to actively relive suffering actively, finding that progress often tramples over the lives of those at the bottom of society. Based off of this, I'd make them Religious, Anti-Industrialist, and either Militarist to Religious (since force primarily serves to relieve future suffering) or Religious to Pacifist (since their religion is entirely about relieving suffering). ESG Sisters of Mercy are already Religious, Anti-Industrialist, and Militarist to Religious, an therefore need no change in my opinion
Sowers: The Sowers have an entire thing in their population quest about anti-intellectualism. They actively try not to delve into the implications of the virtual endless no longer existing and decide to go full blown religious. Also, they are robots yes, but the entire reason they exist is to terraform planets, therefore, I think their Religious, Anti-Scientist, and Industrialist to Ecologist makes sense and should stay as it is.
Harmony: I could see an argument for the harmony being ecologist or scientist. They care a lot about nature, since they _were_ nature. However, they are also naturally very curious. I find their vanilla Ecologist and Scientist to Ecologist a fair way to represent this. However, I do agree that anti-religious is out of place. I think the original idea was that dust is associated with religious politics, so the harmony are anti-religious. It now no longer makes sense, since we associated dust with pacifists, but I also find it's kind of lazy, since the harmony are very religious about finding their home world again. I couldn't find the harmony population quest on the wiki, but I remember it having multiple religious options about how they should deal with dust and religion.
The only real changes I'd make is making replacing Anti-Religious with Religious to Scientist (since believe they need to explore the galaxy to find their home) or something for Harmony, and removing Tikanan anti-pacifist would make sense to me, but I have no idea what I'd even replace it since the tikanan are just mildly intelligent ants.

**Comment by Tat011** [comment]
ooh this is gonna be fun (i'm not being sarcastic i genuinely like discussing lore)
> Epistis: Epistis are not religious or militarist in the slightest. They are not planetary guardians in a military sense, they are planetary guardians in an ecological sense. Their faction quest makes this very clear.

their description reads "Epistis were likely created as planetary guardians, charged with preserving their homeworld's fragile ecology through aggressive defense of its natural wildernesses" it also says "Whether these objectives became corrupted, leading the Epistis to turn on their creators is unknown, but what is certain is that they are a fanatical, dangerous civilization of recycled warmachines ready to take their creed to whoever crosses their path." this references the militarist and religious side, the latter one is refered in the chosen words "Fanatical" "Creed". their minor civ also has the warmonger trait

> Amoeba: The Amoeba in ES2 are very different from the Amoeba of ES1. They are not pacifists, they are very clearly focused on ecology and learning more about the environment and different races. 

i mean i guess the game leaves it sort of ambiguous since it says "the Amoeba developed a strong ecological mind-set, always striving for harmony and balance" (note the similar wording to unfallen stuff) but there's no reason to think they're very different to es1 since every other es1 race is either the same or very similar, either way you could make them ecologist, scientist to pacifist (which is called courious in game) and anti militarist (war isn't very harmonious now is it) instead

> Gnashast: Their lore is that they are racist and hate peace, their political traits are Xenophobia and Anti-Pacifist 

regardless of anything the priority here is to make them different from cravers. were in their lore does it say that they are racists or even that they hate peace? in fact their description states "now entering the space age they are still as aggressive as when they made their first forays onto the tidal flats of their homeworld. Not the most welcoming of races, the Gnashast nonetheless can make strong allies if handled well." either way in my proposal they still have militarist and anti pacifist so i dont see how the identity of the race is being changed here

> Tikanan: Tikanan I could see a real argument for changing, they were originally part of a zoo, but escaped and somehow _very_ quickly evolved to have a civilization, no longer just mindless giant ants. I think Aggressive and Militarist makes sense, but Anti-Pacifists doesn't necessarily feel like it fits because they are more than fine to do their own thing and just not kill anyone. 

Well you could make them militarist, aggressive and ecologist to militarist instead

> Sheredyn: From what lorefather has said, the Sheredyn are more or less the same in ES2 as they were in ES1, however, they are less independent. Sheredyn Militarist to Industrialist doesn't make sense to me since functionally it's the opposite, they have a lot of mining colonies and such that entirely exist to fuel their military. They don't particularly care either way about the environment, so anti-ecologist makes no sense to me. 

It doesn't really matter to me that much if they are militarist to industrialist or vice versa, though my proporsal makes them a bit more interesting voting wise hence why i chose it. Anti ecologist makes them more interesting cuz its something they retain from imperials and also strays away from the trope of "supports X, hates oposite of X" which half the factions do. i mean i don't see how it's a big stretch considering ue also never talked about their environment in their lore and unlike Vodyani did/cravers do they never depleted their planet.

> Mezari: The mezari were probably the opposite of the first trait you mention, industrialist to science. They didn't care about ecology either, they lived primarily in their space ships.

As with shreyedin, just make them industri to science then. also the space ships thing supports my thing since you're not gonna be swayed much by ecological ideals if you don't need/depend or even interact with the environment.

> Pulsos: An argument could be made here that the pulsos are scientists, but it's mentioned that are very independent and love working on their own projects. They still remain curious and open to exploration, but it's mentioned that their major difference from the Harmony (who very much so are scientists) is that they value their independence, yet still value collectivism. 

"This nation, a scientific splinter of the Harmony, seek greater knowledge of Dust in order to better understand the galaxy and seek the Core." also "While most Harmony strive to pass beyond the Dust-tainted galaxy and continue their quest, the Pulsos are a Dust-infected subgroup that have decided to stay and study this mysterious phenomenon." also note the complete lack of any actually industrialist stuff in any of their lore.

> Sisters of Mercy: They are mentioned at first as being anti-scientist, but through the events of the vaulter prologue come to terms with science. They try to actively relive suffering actively, finding that progress often tramples over the lives of those at the bottom of society. Based off of this, I'd make them Religious, Anti-Industrialist, and either Militarist to Religious (since force primarily serves to relieve future suffering) or Religious to Pacifist (since their religion is entirely about relieving suffering). ESG Sisters of Mercy are already Religious, Anti-Industrialist, and Militarist to Religious, an therefore need no change in my opinion

Well i don't know much about EL so... the reason i wanted to change it was cuz i though it was cool to have them be both religious to militarist and to pacifist as their description states them delivering salvation or destruction or wathever but its fine for them to stay as is

> Sowers: The Sowers have an entire thing in their population quest about anti-intellectualism. They actively try not to delve into the implications of the virtual endless no longer existing and decide to go full blown religious. Also, they are robots yes, but the entire reason they exist is to terraform planets, therefore, I think their Religious, Anti-Scientist, and Industrialist to Ecologist makes sense and should stay as it is. 

isnt their quest about how they cant just ignore the fact that their creators are dead and you have to do something about that? if their whole existence revolves around terraforming planets i'd expect them to be ecologist first, the religion aspect serves the ecologist aspect, their religion cant exist without the ecologist aspect, hence ecologist, religious and religious to ecologist. also giving them an industrialist trait cuz theyre robots is lazy and makes about sense as giving organic beings ecologist traits as they need food and a working ecosystem to survive. anti scientist just does the trope i mentioned earlier and as i pointed out earlier they arent really anti intelectuals anyway, also their description states "Sowers are seekers and exploiters of new planets and new systems" and exploration is very much assosiated with the scientist party.

> Harmony: I could see an argument for the harmony being ecologist or scientist. They care a lot about nature, since they _were_ nature. However, they are also naturally very curious. I find their vanilla Ecologist and Scientist to Ecologist a fair way to represent this. However, I do agree that anti-religious is out of place. I think the original idea was that dust is associated with religious politics, so the harmony are anti-religious. It now no longer makes sense, since we associated dust with pacifists, but I also find it's kind of lazy, since the harmony are very religious about finding their home world again. I couldn't find the harmony population quest on the wiki, but I remember it having multiple religious options about how they should deal with dust and religion. The only real changes I'd make is making replacing Anti-Religious with Religious to Scientist (since believe they need to explore the galaxy to find their home)

Wait i thought we couldn't use es1 lore unless stated otherwise cuz this is different or something, either way, the whole nature thing seems to be completely ommited from any and all their es2 descriptions so you can understand why i didnt know, i think doing the harmony change you said to harmony is fair enough though its gonna remain confusing to anyone not in the know.

**Comment by Tat011** [comment]
you also didnt mention remnants or horatio, you said that all of them were wrong so is there something wrong here you forgot to add or what?
