### ISSUE TITLE
Make all Behemoths stackable within Fleets

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#12]
Slightly bugged, Max Fleet CP won't appear while a Behemoth is in a squad

**Comment by wakystuf** [comment]
I tried testing this and couldn't get econ behemoths to stack; was this reverted later due to some other bug it caused, or something else? Maybe I just didn't do it right.

**Comment by Eighth-of-Third** [comment]
We made eco behemoths un-stackable later due to balance issues; namely, that Hissho could put their starting guardian hero on their starting eco behemoth, get 10 xp per turn, and get a serious hero level advantage that they really didn't need. Eco behemoths weren't stacked with anything otherwise, so we didn't see any reason not to make them unstackable.

**Comment by wakystuf** [comment]
Ah, got it. I now see the separate issue explaining that; sorry about that! That's what I get for doing only the V1.0 topics first. I'll clarify that on the wiki
