### ISSUE TITLE
UE/Mezari Quest Improvement "Who's Yuri?" Didn't get the buff Magnetic Field Generators Got

### ISSUE THREAD

**Issue by Provolonage** [captaincobbs/ESG-Mod#1217]
The scientist path quest improvement for UE didn't get the buff Magnetic Field Generators got despite them being basically the exact same improvement, we can either change it to be more unique or just give it the same buff, I'd also suggest bumping the indy cost down a tier since the improvement its based off of is already really weak even with the buff. Its not a terrible buildings but its an early quest reward you find your self building  on turn 30-40 because its very low yield for its investment, at a time where most buildings are very high yield for the investment.

**Comment by Arpharnator** [comment]
I'm not sure if you're right, selecting traitor's reach and then getting this building makes a lot of extra science. Furhtermore I wouldn't underestimate the building in general, I think it gives +1 science, +3 on anomaly which is pretty decent at buffing your science output to ignore graviton for a bit more and focus on industry with predictive logistics.

I also don't want to buff things just for the sake of bringing them up to par with another, especially if it's a pointless comparison since you can get both building and snowball your science pretty well. The only place to compare this building is with the other quest rewards.
I want to avoid giving too much numbers everywhere, the game is already fast enough as it is.

**Comment by Provolonage** [comment]
it definitely synergizes with traitors reach a lot but its really not that great, +3 science on every pop isn't that great and it isn't great for its cost either. I think the UE path gives an empire wide buff of +25 indy per sd level which scales better with the UE+faction affinity, give more yield overall at probably every point of the game and doesn't need to be built or have upkeep. Sure Ghallafire is pretty bad, but Sheridyn has the best synergy with all of UE's faction stuff so its fine, Mezari has the biggest shift in gameplay but doesn't feel like they get as much as the other two.
