### ISSUE TITLE
Luxury/Development Rework

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#124]

**Comment by Arpharnator** [comment]
Fix T3 luxury effects not applying, both in vanilla and with luxury rework enabled

Find a way to make the bonuses show up when you choose which luxury to put

**Comment by Arpharnator** [comment]
Fix ionic crystals not working

**Comment by Arpharnator** [comment]
stuff that does not work is the Lost cities (+2 hapiness per pop), ionic crystals.

There lacks some descriptions tho : 
![image](https://user-images.githubusercontent.com/49691625/103777134-b9282400-5030-11eb-846c-ab2015cd57bb.png)
![image](https://user-images.githubusercontent.com/49691625/103777143-bb8a7e00-5030-11eb-8d32-244870247875.png)
![image](https://user-images.githubusercontent.com/49691625/103777146-bdecd800-5030-11eb-9c39-837c88934a18.png)

Everything works good otherwise

**Comment by Arpharnator** [comment]
unless I suck at testing it works
