### ISSUE TITLE
Make Kalmat give +2 industry and +1bandwith instead

### ISSUE THREAD

**Issue by Tat011** [captaincobbs/ESG-Mod#1242]
yes im doing this again and its cuz this happened to me last game which proves the issue i raised last time
![20220604190258_1](https://user-images.githubusercontent.com/99352011/172060524-e82f083e-6dd7-4ff3-8d70-01b1f2f95743.jpg)
As you can see i was receiving a huge ammount of bandwith due to the pop but it wasnt being used for anything since the empire above me was an ally and even if i hacked them anyway their capital was too far away (of course the reverse is also true), below me was uc whom you cant defend against their hacking no matter what and the middle was also too far away. So i never got hacked by anyone whom i could defend myself by using bandwith
This means that not just the pop was useless but their collection bonus was also useless as well since its also just more bandwith.
This shows what i said last time that they're incredibly situational, even more so than militarist factions nowadays and need something else.

**Comment by NoProblemWithThisAcc** [comment]
So I looked on my Population Point Buy Cost and Tier Splicing spreadsheet and it turns out that you are correct. Going down to 1 bandwidth and 2 industry would be an even trade. Note that Mavros and Xirmisala are actually worse at 3 effective FIDS rather than 4. Also UE Mezari, UE Imperials, Hissho, and notably Umbral Choir are also at only 3 effective FIDS. Bringing all pop to a minimum of 4 does sound like better balance, although whether this means the current trait sets would need adjusted as a result is up to other players. Obviously +1 industry to all of them would mean nothing if they gained a horrendous -10% industry trait, for example.

But about bandwidth, you can use it to slow down UC hacks, making you a less appealing target. UC players have to weigh their options of hacking you rather than someone else. Extra hack turns means wasted colonization for them (unlike other races that can just spam colony ships). This means they *should* choose to hack the direction away from you. If you are saying UC is hedged in so they are only touching your empire, that's a map generation problem. We can't directly fix that but we can work around this by giving void hacking at the start (meaning they will want to hack across empty space to somewhere else rather than sticking to just starlanes). Also having spare bandwidth means your capital (or edges) can be fully defended without getting overloaded.

**Comment by Tat011** [comment]
having more defensive programs is useless since i never got hacked by anyone other than uc (cuz as i said everyone was too far away) and uc never hacked my capital (cuz it was too far away even for uc)
and having just 1 industry and 1 band would make this pop straight up bad, its ok for uc for the same reason its ok for ue, its the mayor pop.

**Comment by wakystuf** [comment]
Yeah that seems fine. I'll assign it to you for now, but I'll close this Issue if it sits for a week without any updates
