### ISSUE TITLE
Unfallen pop col vs anom max pop quest reward

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1243]

**Comment by wakystuf** [comment]
What exactly is this issue? Is this something I said I would do? I can't remember

**Comment by captaincobbs** [comment]
Nerf the science population collection reward

**Comment by Provolonage** [comment]
why do you buff the pop slot on anom to 2, the reason why its bad is because unless you get really lucky with anoms it isn't worth going, but I do think it could use a small nerf, also while I'm here is there anyway to make center of light and life count pop types on empire so you dont have to spread minors that don't offer unfallen much benefit, id be fine with nerfing the sciecne per pop to 20 from 30 if we did this.

**Comment by wakystuf** [comment]
Can someone explain using complete sentences what exactly is being proposed here? I strongly suspect that Cobbs' comment about the science reward is separate from what Arphar originally meant

**Comment by Arpharnator** [comment]
basically it's to weight this particular unfallen quest reward.
See if it needs nerf or nah

**Comment by wakystuf** [comment]
Oh, I see. Yeah the science one probably is a little bit overtuned right now; I see what Cobbs was saying. I'll add this one to my list

**Comment by wakystuf** [comment]
I'm going to start small on this one and only mess with the flat portion, cutting from 10 to 5 (but leaving the 1% alone). If it's still overtuned then we can revisit
