### ISSUE TITLE
Increase science victory requirements

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1271]
4 techs to unlock the endless tech stage, instead of the current 3.

**Comment by Provolonage** [comment]
nah if you nerf science convo it will slow it down alot + eco victory is already faster so this seems unnecessary

**Comment by Arpharnator** [comment]
the convo is only getting nerfed by 9%, which isn't that much
and about eco victory then i guess it needs to be increased again?

**Comment by Provolonage** [comment]
nah eco victory is really high already the issue is science victory really isnt that fast its jsut everyone focuses science super hard basically every turn of the game, nerf convos then lets wait, also will the UI in the tech tree update properly if you change the reqs?

**Comment by Arpharnator** [comment]
I think it can be a good idea to wait to see what the result from the convo nerf is.

As for the UI it should update automatically if i tell it it needs 1 extra tech to open the stage

**Comment by wakystuf** [comment]
Yeah the GUI adjusted properly in the past when I made the T4 eco quadrant require an extra to unlock. I haven't tested with victory techs but I assume it would be the same.

I would probably wait to see how the conversion impacts it and then go from there; for most factions, nerfing from 75% to 66% will be pretty significant.

One other thought is that if we do conclude that we still want to slow things down, we could simply increase the costs of the victory techs instead of requiring more T5s to unlock. Many of the T5 techs are shockingly bad, so requiring more of them will indirectly create more work since then we'll need to add content to some of the T5s to make them worth considering

**Comment by Arpharnator** [comment]
so the nerf is from 75% to 66%, not 100% to 66%.

We could also do that.
