### ISSUE TITLE
Nerf Ind to science and dust convos

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1272]
to 33%and 66%, respectively for T1 and T2

**Comment by NoProblemWithThisAcc** [comment]
It's OP because it's useless early on (as well as too powerful late game). Perhaps address both parts of the imbalance? We already have the 'in the queue' mechanic for other things, so -33% industry (which becomes science) and then -66% industry (which becomes science) would force you to still build other things and it would slow down the science gains.

But more importantly it would make it usable early because now your queue isn't totally wrecked. Or maybe -25% and -50% for someone who wants the industry to run the 50% dust and 505 science at once.
