### ISSUE TITLE
Horatio quest changes

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1273]
industr path : 
6 systems to level 2
3 ships of 100 defensive power instead of 5
Removed the second fleet

ecologist path : 
10000 dust insead of 1000 to spend on the curio

religious : 
increased the amount of extra influence to make by 50, so you need 100 extra inf instead of 50
reduced hero level requirement to 8
the 40% Experience per turn reward becomes +40% experience multiplier

**Comment by wakystuf** [comment]
This all seems reasonable to me; I linked it to the relevant PR. Can you also update the quest diagram accordingly for the changelog?

**Comment by wakystuf** [comment]
Also don't forget to document the XP change for the religious quest reward

**Comment by Arpharnator** [comment]
the +40% Experience per turn becomes +40% Experience Multiplier for the horatio quest reward

**Comment by Kil10naire** [comment]
If someone could make the picture like the ones for the other faction quests, that'd be great.

**Comment by wakystuf** [comment]
@Arpharnator I think was supposed to do that

**Comment by Arpharnator** [comment]
one day

**Comment by Arpharnator** [comment]
[Horatio_Quest.xlsx](https://github.com/wakystuf/ESG-Mod/files/9277414/Horatio_Quest.xlsx)

**Comment by Kil10naire** [comment]
Hey, funny story, I don't have Excel so I downloaded the file and converted it to a PDF online, but either the original file is messed up in some way or I have incredibly bad techno-vibes because it is completely cursed. 

![Horatio quest eco](https://user-images.githubusercontent.com/97924925/183409243-8f671ca1-2975-4732-838f-8117888df010.png)

![horatio quest indy](https://user-images.githubusercontent.com/97924925/183408315-47e54b9c-2d3a-4ce8-a809-e49025027e82.png)

![horatio quest rel](https://user-images.githubusercontent.com/97924925/183408333-b65b3c0f-8645-496d-8c86-d98916144f54.png)

I can upload it like this but idk bros

**Comment by Arpharnator** [comment]
how about you get excel
