### ISSUE TITLE
Add Horatio-Only Minor Pop Curios

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1282]
@Arpharnator  Let me know what you think about this:
* Create a quest in the Horatio main quest that spawns curios near-ish to the Horatio home system
* Curios would be defined as 3 new ones, with a detection visibility of 2, 3 and 4
* Spawn 2 T2s, 3 T3s and 4 T4s (can adjust the numbers as needed)
* The curio droplists would include only minor pops, with different lists for each tier (which would reduce duplication)
* Would need some TBD balance offset, likely related to weakening T3 collection bonus
* Would need the lists of pop by tier (Pulsos and Bhagaba to be excluded from all lists, since they are already on the capital). Hopefully a Horatio player can generate those.

**Comment by Arpharnator** [comment]
I think this can be a good idea
When this gets done a bit of internal testing will be needed to make sure it flows well.

**Comment by Eighth-of-Third** [comment]
> Would need the lists of pop by tier (Pulsos and Bhagaba to be excluded from all lists, since they are already on the capital). Hopefully a Horatio player can generate those.

I've been informed that this part needs some better support for custom factions. If a custom gene hunter doesn't start with Pulsos and Bhagaba, they still won't spawn in in the quest curios.

**Comment by wakystuf** [comment]
That would be a pretty significant pain to code; I think we'd have to make new ones just for the custom.

Also, it's not like said custom faction is meaningfully worse off anyway; they'll simply get Amblyr, Pilgrims or whatever instead of Pulsos and the overall power should be the same.

**Comment by Provolonage** [comment]
Yeah I agree with Waky, this isn't really an issue we could just add Pulsos and Bhagaba to the pool anyway since I think ratio gets too many unique pop types anyway currently and can't effectively splice them all without trolling, the chances of getting a Pulsos or Bhagba anyway are far less then just getting a duplicate of a pop you jsut got from the quest curio pool anyway, I got really lucky and got 3 nirnis from mine before, its not a big deal.
