### ISSUE TITLE
Vodyani Planet Cracker time seems to be broken

### ISSUE THREAD

**Issue by Wingouu** [captaincobbs/ESG-Mod#1314]
Whenever I use a vodyani planet cracker the base number of turns is 3 turns and when I use the modules to reduce planet cracker charge time it goes down to 1 turn even though it says the minimum is 2 turns. This means that I can just send a planet cracker into a system and crack it when the turn ends. I believe the base number of turns for a planet cracker is supposed to be 5 turns and can be reduced to a minimum of 2.

**Comment by wakystuf** [comment]
Yeah, I see what you mean with this. Unfortunately, I think there must be something going on that's hard-coded, because the variables I can manipulate are showing a floor of 2 and yet it's letting me use it after only 1. I did some poking around and can't seem to find anywhere in the accessible code that it's moddable

**Comment by Arpharnator** [comment]
if im not mistaken it's countund down 1 turn before, while in travel for some reason

**Comment by wakystuf** [comment]
I think it's actually a gamespeed scaling problem, since it works fine on Normal. However, the part of the code that regulates this is (I think) locked away someplace that I can't find, so I can't prove it

**Comment by wakystuf** [comment]
Closing simply because I think this is not fixable
