### ISSUE TITLE
Rb and Vaulter quests still bugged

### ISSUE THREAD

**Issue by Provolonage** [captaincobbs/ESG-Mod#1315]
Rb quest to build 3 improvements still doesn't work on the home system and vaulters still have to build 3 ship/defense improvements, then sell 1 and then the quest will pop.

**Comment by wakystuf** [comment]
OK, this should now be fixed. Looks like the RB one previously was still requiring 9 buildings, but it counts the home system buildings. I tried to make it NOT count the home system buildings and was not successful, so instead I increased the objective to 4 from 3. Overall I think that's a net buff since there are 2 home system buildings; I almost did 5, but then it would be legit unreasonable for any non-Home system.

For the Vaulters, the problem was purely a technical one related to the ship and MP buildings actually being 2 different categories of building, so there's extra logic to account for the different combinations that are possible
