### ISSUE TITLE
Scrapping related changes / Minor Empire changes

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1365]
Divided stress per turn on hard mode by half. It was proving extremely excessive since the changes to scale minor stress with gamespeed.
Greatly increased budget contribution to ship dust stockpile. This should effectively allow for the minors to properly field their fleets the moment stress allows it.
Made minor fleets significantly stronger later on. Slightly increased stress requirements starting from the third stress threshold. These changes are aimed at making scrapping fleets take losses and be overall far less profitable. This also allows to put a decent price on a system with many advanced buildings and potentially autonomous administration.
Raised minor quest giving action requirement to 75 relation points in order to keep in line with the better buildings.
The action allowing to gain a fleet from minors has had its cost brought up to 75 from 25 and cost 5 pops instead of 3. Will perhaps need to be changed again to be more costly.

**Comment by wakystuf** [comment]
Update: also fixed Arphar's localization from the error message on quests that says "relations must reach 50 points" --> 75 now. Implemented in 5 of the 6 ESG languages, since oddly Brazilian already had 75 instead of 50.

No need to document separately, since we're catching this within the same release
