### ISSUE TITLE
Various Issues at the behest of Light

### ISSUE THREAD

**Issue by Kil10naire** [captaincobbs/ESG-Mod#1411]
Earlier Light contacted me regarding creating issues for various things in the mod, and since he didn't want to spam issues on the GitHub, I somehow let myself get scapegoated into doing it in his stead. Hopefully if I misconstrue his original points, he shows up to correct me and facilitates the discussion.

Since I also don't want to spam the GitHub, I decided to include all of the ones I wrote down in one big issue. If that's an issue (lol) regarding delegation of duties and marking of progress, unlucky. 

1. The new Warning -> Prepare for War -> Declare War chain is somewhat awkward to use due to there being no visible timer. A rudimentary and potentially cluttering solution proposed involving several different versions of "Declare War". "Declare War (5) Turns", "Declare War (4) Turns" "Declare War (3) Turns", etc. All of them, save for the turn-accurate one being grayed out, thus acting as a makeshift timer that can be easily kept track of. An alternative solution could be to make the Declaration of War automatic, so there's no extra work on the user's end. 

2. Luxury Quest Reward Change. Regarding various Quest Rewards that grant a flat amount of a random luxury, the change proposed is to let the player choose their reward. Or, failing that, let them choose from a selection of different rewards, a-la the Vodyani Quest Reward that lets you select luxuries from a category, which basically does the same thing. Failing that, have them act like the Scavenger Capstone skill, where you get a luxury resource that you have used in System Development. 

3. Quest Law Requirements. Regarding various Faction Quests wherein you are required to enact X+(Y) laws of a certain party. The change proposed is to have them be a flat amount of laws, so they are less of a micro/knowledge check. Good players are just going to unequip their laws right before they get the quest step, whereas newer players won't know to do that.

4. A Penumbra bug, likely vanilla. The situation: You attack an enemy fleet and then the faction requests you stop attacking their fleets, at the same time one of your hacks gets traced and you are afflicted by the "Blackmail" penalty. In this situation, with both pop ups active, the "stop attacking our fleets" prompt is un-deniable because the game treats it as such due to the "stop hacking me" prompt being un-deniable. However, if you accept the "stop hacking me" penalty, you are once again able to deny the "stop attacking our fleets" request.

There were probably more but I was spacing out at the time.  Also I'm leaving it untagged because I don't remember the etiquette on how I'm supposed to tag things, other than to remove "Needs Documentation".

**Comment by NoProblemWithThisAcc** [comment]
Mwuahaha
1. Correct but we can even hide the unused ones the way we hide the current declare war option, so the user wouldn't know there are several copies with different numbers (ie in 3 or 2 turns) and would think the same entry is dynamically counting down.
2. Props on the vody thing. This RNG annoyance is so bad I save scum in single player, lol.
4. Issue found in vanilla and I doubt we have fixed it, if it is fixable.
5. Small localization issue (accidentally similar to 3.) where the English is ambiguous: Quests should say "Have x laws active at once" because "pass 2 laws" implies that passing a second religious law isn't enough if you already have one active, because you haven't passed the first once since you started the quest, ie. I only took 1 action, not 2 as expected by using the active voice.
 6. Also another localization issue in Nakalim because I was checking Benthic Gems for the changelog verbage: 
Relic collecting should say: "only 1 can be collected at a time here." Without the 'here' in there, it would suggest only one scout may collects at once even on different systems.
7. Since the above is intended behavior (I verified), what's the harm in allowing 3 scouts to collect 3 relics in 3 turns, one after another, 1 turn each rather than 3 scouts in 3 simultaneous systems taking 3 turns? It will allow you to clog up multiple scouts' actions, which is a bit of a noob trap. It's a small buff considering how painful beliefs not breakthroughs is, it should be fine, right?

**Comment by wakystuf** [comment]
My thoughts:
1: Unless @captaincobbs can think of a way to do this, then I don't think it's possible. There's no accessible variable (that I know of) which records the time since Warning issued, age of Warning, etc. In general, it's impossible to force the game to remember things if it doesn't already.
2: What is the luxury quest? In general choosing rewards is impossible--the Vody one only works because it's technically selecting among 4 altogether different quests (all of which have the same goal), but that collapses if there are other choices. It's also a huge pain.
3: Hmm...I think in some cases this may have already happened. Are there still quests that are not set up this way? That should be pretty doable to fix.
4: I don't think this is moddable, but it also might be intended behavior. I think "Blackmail" simply forces the victim to say "yes" to the next diplomatic demand they are given (from the Blackmailer), not necessarily only to stop hacking. I may be remembering wrong, however. It's been a really long time since I Blackmailed anyone or was Blackmailed.
5-6: This sounds like Awakening stuff? If so, the solution is to disable Awakening.

**Comment by NoProblemWithThisAcc** [comment]
Questions:
1. The current implementation creates a new, non-"(Surprise)" entry in 10 turns, if you've prepared for war. Can we make 9 visible but greyed out (or no cost/effect) timer-controlled entries, each lasting 1 turn that say "(wait 9 turns)" and then "(wait 8 turns)", etc? Or is there a limit of spawning 1 entry upon the player taking 1 action?
2. I need to go do a vody run to see how it currently looks. I figured it would be a pain to make 8 copies of 2-3 paths. If I could get an exclusive list of such quests, I'd be tempted to do the pasting and editing myself. Is the 'Your first System Development luxury' implementation in the Scavenger capstone doable, say for the (winner's) multi-empire quests like Words in Private?

Comments:
3. Cool, I'll keep a look out. I wrote out that note during either an UC or Riftborn play-through.
4. I'll test if blackmailing is just for 1 request of any kind. I hadn't considered that possibility.
5. is just a tooltip change. Unless I hear otherwise, I'm just going to adjust wording like that in tooltips , once I start making branches and requesting merges, going forward rather than posting the pictures here or in Balance Senate.
6. Some people main Nakalim (not me). I'm confident I can locate, change, and test this line properly once I get back into the swing of things. It's a very slight buff but I consider it more so QoL.

**Comment by wakystuf** [comment]
1. I don't think that's possible but I can think about it some more. It MAY be possible to cascade 9 different constructibles all with different durations (9, 8, 7...2, 1) and then peel off one each turn, but it will be quite tricky at a minimum.
2. I don't think it's possible to mirror the scavenger skill--the rewards are just pulling from another database and not looking at the player's stuff (vs the hero exists within the Empire and therefore can reference the empire's SD selections)

**Comment by wakystuf** [comment]
Yeah I don't think the diplo thing will work with multiple cascading constructibles, since they won't auto-trigger. In theory one could set up a system where there are 10 different ones called like "Declare War in X turns", but then the player would have to actually click on it every single turn (which, in addition to being QoL cancer would screw them over if they missed one). Otherwise, the "effect" of the 1-turn lag on the timer wouldn't trigger.

**Comment by wakystuf** [comment]
OK this miiiight be doable after all. I just figured out how to track the duration since Prepare for War, so referencing that (newly created) variable may make this possible. Likely still a pain to do, but in theory should no longer be entirely impossible.

**Comment by wakystuf** [comment]
Done.
![image](https://user-images.githubusercontent.com/79942510/226790190-c2316512-af8f-409e-a264-1790a1640fe8.png)
