### ISSUE TITLE
Fix Academy Relations always being Hostile

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#1465]
Was fixed in #1464, just adding this so it can be documented

**Comment by 107g** [comment]
![AcademyHostile](https://github.com/wakystuf/ESG-Mod/assets/51477716/070f03fd-016e-463b-8b22-9daa756a168f)

Academy relations is positive and is yet marked as 'Hostile'

When looking through the Diplomacy/DiplomaticRelationStates[Academy].xml file, you can see that there are 3 DiplomaticRelationState definitions, one for Neutral, one for War, one for Ally. None of them have the MinimumRelationPoints Attribute that is found in the vanilla version. Since Hostile and Friendly relation DiplomaticRelationState definitions are not in the mod, you can either be Hostile or Friendly with the Academy. Defaulting to Hostile as you don't have the 15 Points necessary to be considered as friend.

**Comment by captaincobbs** [comment]
> ![AcademyHostile](https://private-user-images.githubusercontent.com/51477716/317525008-070f03fd-016e-463b-8b22-9daa756a168f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NDU4MDksIm5iZiI6MTcxMTc0NTUwOSwicGF0aCI6Ii81MTQ3NzcxNi8zMTc1MjUwMDgtMDcwZjAzZmQtMDE2ZS00NjNiLThiMjItOWRhYTc1NmExNjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDIwNTE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZDRiZGEwYzJjNDA1YmNiZjE5NmNlMzgxN2VhNjE5ZDJlYTc3N2RmM2Y1YjAyYjlhOTQwZTVlMTYzMjVkNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W27XrEFS4N8F3pvh6_cHUQBPQWKjrTa0I_dxV6iZjfA)
> 
> Academy relations is positive and is yet marked as 'Hostile'
> 
> When looking through the Diplomacy/DiplomaticRelationStates[Academy].xml file, you can see that there are 3 DiplomaticRelationState definitions, one for Neutral, one for War, one for Ally. None of them have the MinimumRelationPoints Attribute that is found in the vanilla version. Since Hostile and Friendly relation DiplomaticRelationState definitions are not in the mod, you can either be Hostile or Friendly with the Academy. Defaulting to Hostile as you don't have the 15 Points necessary to be considered as friend.

How would you like to be credited in the list of ESG contributors?

**Comment by 107g** [comment]
Uhm, I dunno? Not used to ppl asking me this. Maybe credit me in the next minor release notes or something?

**Comment by captaincobbs** [comment]
> Uhm, I dunno? Not used to ppl asking me this. Maybe credit me in the next minor release notes or something?

I more mean like, what would you like to be credited as? You'll be added to the list of contributors for this :)

**Comment by 107g** [comment]
Ah! I see :)
Credit me as 'StatusAtlas_'
