### ISSUE TITLE
Change Cravers capstone skill for Hissho and UC (Endless Consumption): +10 FIDS per pop instead of 200% FIDS

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#161]

**Comment by wakystuf** [comment]
How did this one end up being resolved? I couldn't find a reference to it in HeroSkillDefinitions.xml, but maybe it's someplace else?

**Comment by captaincobbs** [comment]
Hm this may have accidentally been skipped

**Comment by wakystuf** [comment]
For what it's worth, I would suggest applying this change for all factions, as the current trait is quite OP for any non-Craver. 4 key points:
1) +200% is just...a lot.
2) That 200% is applied at the best possible level: after all +X per pop effects, such as AI Labor, are applied, but it still gets counted in "from Planet" and therefore multiplied again with all other % bonuses (ex: vanilla FIDS behemoths, tier 3 luxuries, etc)
3) Non-Craver factions don't care about the depletion cost, and simply need to relocate the hero every dozen turns or so to avoid ever having a penalty
4) Even if a player DID care about the depletion cost, one could still use a behemoth to simply repair 10 depletion points per turn (more than the 8 added by Endless Consumption). Yes, this consumes a behemoth, but if it enables permanent +200% (counted in base) that is far better than the 25% FIDS (which was nerfed because in the mod!) in vanilla

As one example, I recently had a system around T75 (Normal speed) which went from 6.5k production to 20k+ simply because I leveled up my Craver hero; that game was pretty close up until then, but now I'm almost certainly going to win no matter what else happens.

**Comment by wakystuf** [comment]
I've uploaded this one as well, so I'll mark as "in testing"? That way somebody competent can confirm I didn't mess anything up
