### ISSUE TITLE
Make the effects of some minor faction quests not impossible on higher gamespeeds

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#241]

**Comment by Arpharnator** [comment]
Doesn't work
![image](https://user-images.githubusercontent.com/49691625/103135640-e59b8200-46b9-11eb-8ef8-702a8830d394.png)

**Comment by Arpharnator** [comment]
still does not work
![image](https://user-images.githubusercontent.com/49691625/103172246-6beacc00-4852-11eb-80a9-34f13e6f0fb0.png)

**Comment by captaincobbs** [comment]
Quests to test:
MinorFactionQuest05 (should have a flat 6 turn req)
MinorFactionQuest13 (should have a flat 8 turn req)
MinorFactionQuest16 (should require 15% instead of 30)
MinorFactionQuest17 (should have a flat 8 turn req)

NOTE: Turn requirement should be the same as vanilla on quick. Some of these quests require like, 50 turns on endless speed, which is terrible. 30% System Militarist support is near impossible on endless speed for non militarist factions because support scales inversely with game speed.

**Comment by captaincobbs** [comment]
Testing in luxury-rework

**Comment by Arpharnator** [comment]
everything works, apart from : 
![image](https://user-images.githubusercontent.com/49691625/103896976-1dabb780-50f3-11eb-9960-0ee4a6e8e601.png)

**Comment by captaincobbs** [comment]
Fixed, confirmed works

**Comment by wakystuf** [comment]
Is there a list somewhere of the different quests and changes?
