### ISSUE TITLE
Riftborn Questline Rework

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#294]
https://www.reddit.com/r/EndlessSpace/comments/kmpgur/quest_wants_me_to_increase_the_level_of_a_lvl_4/

**Comment by wakystuf** [comment]
What is the status of this one (and what was the change)? It seems to be Closed, but also labeled as both Bugged and In Progress.

**Comment by captaincobbs** [comment]
I believe it's finished but I wasn't involved

**Comment by Mermixer** [comment]
theres still a bug with the industry saving not applying after you took the pop cost reduction questlines

**Comment by wakystuf** [comment]
OK. I'll leave the Needs Documentation tag for now, and put it on the wiki once it's resolved

**Comment by Doruk-Coskun** [comment]
@wakystuf  This Issue combined with other RB issues in 1.3.1 focuses on making the RB questline smoothed out in terms of Quest requirements and rewards. Approval buildings are reworked to give Approval per Major or Non-Major pop. Quest Rewards are nerfed to be more appropriate to the time they are completed in a game. Most importantly Final RB Quest rewards are changed. Tainted Dust reward which gives +4 dust per RB pop reworked to give +3 movement point on every ship. +4 industry is nerfed to +3. +3 Strategic on every deposit reduced to +2. If you want more detail about the changed quest requirements I can also specify them. Finally this change also includes that the RB colonizer has 3 support slots rather than 4 now.

**Comment by wakystuf** [comment]
OK, thanks. below are the ones that I already documented from finding them in the code:
  * Main population dust bonus reduced from 5 to 2 dust per pop
  * Biophobic trait happiness changed from +10/-2 on Sterile/Fertile to +8/-3 (no change to pop slot effects)
  * Industrialist law 1 reduced from 10/15 industry per outpost to 5/10 in non-republic/republic
  * Reduced final quest reward (Backlash/crush chapter) from +4 industry per pop to +3
  * Reduced final quest reward (Backlash/appease chapter) from +3 strategic resources per deposit to +2
  * Number of colonizer support slots reduced from 4 to 3 (added this one from your commentary above)

It sounds then like the rest are:
  * "Approval buildings are reworked to give Approval per Major or Non-Major pop. Is this a per pop happy bonus, or something else?" I believe before they were +5 happy if major pop (sensory deprivation) and +5 happy if minor pop (bespoke architecture), flat?
  *  "Quest Rewards are nerfed to be more appropriate to the time they are completed in a game." What was this one?
  * "If you want more detail about the changed quest requirements I can also specify them." Yes, that would be great, and I'll add.

**Comment by Doruk-Coskun** [comment]
@wakystuf 
- Approval system improvement rewards were one-time +5 flat approval buildings now they give per pop.
- Basically some early RB Quests rewarded huge quantities of Tier 2 strategic and luxuries now they give either huge amounts of Tier 1 strats or Tier 1 luxuries or low quantity of Tier 2 strategic or Tier 2 luxuries.
- Now that I thought about it they are pretty detailed to include. Mostly first RB quest requirements are reduced and aligned with other factions quest requirements and the other quests are adjusted to make more sense for the time they are expected to be completed (Assigning the seeker hero to a fleet quest reworked so that the Fleets offensive power makes sense with what you can build at that time in the game etc)

**Comment by Doruk-Coskun** [comment]
1. +2 per major pop and  the other one is +3 per non major pop.
3. Nah not needed.

**Comment by wakystuf** [comment]
OK, great. I've just documented the per pop approval changes.

Can you point me to where in the code I can find the quest requirement changes? I'm happy to list them myself if needed.

**Comment by captaincobbs** [comment]
In ESG and Vanilla, they are located here:
Quests/QuestDefinitions[TimeLords].xml

**Comment by wakystuf** [comment]
Thanks! I'll take a look

**Comment by wakystuf** [comment]
OK, this file was more complicated than I'd expected, so make sure this sounds right (I'm excluding the changes that were already documented in prior versions):
-Increased chapter 1.2 approval requirement for X turns from 60 to 85
-Increased chapter 1.2 science requirement from "Colonize a new system and raise its science to 60" to 125
-Increased chapter 2 fleet offensive power requirement from 400 to 4000
-Increased chapter 4 (ecologist) minimum number of laws required to be passed to 2 (or N+1, if 2 are already passed)
-Increased chapter 4 (pacifist) requirement from 1500 dust to 10 each of all 6 strategic resources

Also, what do these changes mean?
<Expression>SumProperty(Context, @'ClassEmpire/ClassPopulation,PopulationNonMajor', PopulationCount) + 12</Expression> (formerly 15 instead of 12)
<Expression>Property(Context, @../ClassEmpire, GameSpeedMultiplier, true)*10</Expression> (formerly 18 instead of 10)
<Expression>Property(Context, @'../ClassEmpire', GameSpeedMultiplier, true)*10</Expression> (formerly 20 instead of 10)

**Comment by captaincobbs** [comment]
Was this change ever finished by the way? Is there more coming in future updates?

**Comment by Arpharnator** [comment]
This stuff is finished, even tho rb quest may still move, but not rn

**Comment by wakystuf** [comment]
Oh, @Arpharnator did you make these changes, and you're confirming that my summary above sounds accurate? If that's true, then I'll go ahead and post to the wiki instead of waiting to hear from Chaos. Just wanted to make sure before I post.

**Comment by Mermixer** [comment]
Increased chapter 2 (industrialist) fleet offensive power requirement from 400 to 4000
thought the vanilla value was 3k, increased to 4k now

**Comment by wakystuf** [comment]
OK, great. Documented. 
@Mermixer , the code said 400, but maybe it was updating to something higher if you already had a fleet with 2k+?

**Comment by Mermixer** [comment]
huh i just checked for vanilla (made me very glad we dont play vanilla) and it does indeed say 400, at least when i dont build a fleet
