### ISSUE TITLE
Nerf OP Minor Faction Traits

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#298]

**Comment by Arpharnator** [comment]
![image](https://user-images.githubusercontent.com/49691625/104637212-c97d7600-56a4-11eb-8041-e19da8605023.png)
Very strong as it can turn the tide of the early game in your favor
![image](https://user-images.githubusercontent.com/49691625/104637261-dac68280-56a4-11eb-8b91-98f6ca2c58d1.png)
Extremely strong because flat food on sterile is insane, and the other bonus makes reducing anomalies worthwhile.
![image](https://user-images.githubusercontent.com/49691625/104637374-00ec2280-56a5-11eb-94b5-e09df71949a6.png)
Broken as fuck, needs nerf ASAP (breaks UC).
![image](https://user-images.githubusercontent.com/49691625/104637725-7526c600-56a5-11eb-8d1d-0309e671228b.png)
Potent bonus, always useful
![image](https://user-images.githubusercontent.com/49691625/104637813-94255800-56a5-11eb-88f9-61f3f80d1a87.png)
Gives free UE quest reward and +50% bonus luxuries on fertile, very broken.
![image](https://user-images.githubusercontent.com/49691625/104638032-e797a600-56a5-11eb-8b27-0d4217edc5d0.png)
Much akin to Sefaloros bonus, but for strategics.
![image](https://user-images.githubusercontent.com/49691625/104638278-41986b80-56a6-11eb-9b9d-470f9e5f49f0.png)
Extremely strong as a flat bonus.
![image](https://user-images.githubusercontent.com/49691625/104638327-5117b480-56a6-11eb-9db1-2e0760ad8c9b.png)
Decent, I put it here because it once again fits the trope of very good early ehh late.
![image](https://user-images.githubusercontent.com/49691625/104638431-7278a080-56a6-11eb-9dc5-83c7d685f283.png)
Solves approval in some circumstances.


Also don't forget deuyivan's trait giving base 5 science on planets with lower science than 5.

**Comment by NoProblemWithThisAcc** [comment]
Some are too powerful. Perhaps the best way to balance the MUST-HAVE nature of them is to simple make them pickable faction traits like your legends mod.

Then there is no "I want to quit because I didn't get this faction assimilation". Fighting over those unique resources causes a lot of ire in multiplayer, it seems.

**Comment by Doruk-Coskun** [comment]
Tinkers and tinkers: 1 -> 0.5 per curio searched
Workspace Oddity: 25 -> 20 industry per anomaly
Mines over matter: 40 -> 30 science...
Profitable Exploitation: 40 -> 30 dust...
Hunting Culture: 20 -> 15% damage on weapons...
Soil Healers: 25 -> 20 food per sterile, +2 -> +1 FIDSI....

**Comment by wakystuf** [comment]
For what it's worth, I'd probably have nerfed Thinkers & Tinkers I even more (like 0.1 or something). With the UC and the Riftborn (for different reasons), they are totally insane. 
-The UC can easily explore 100-150 curiosities, and spam 15-20 sanctuaries, for a  total of 1500-3000 incremental production. 
-The Riftborn get the bonus on their outposts, such that they can colonize in 1-2 turns. That's inherently quite good, but it's far better if one is combining that with the abuse of the T1 industrialist law to spam infinite happiness. Essentially, each random awful 1-2 planet system will generate 35 happiness for 5 turns, then go dormant for 1-2 turns while the outpost re-colonizes. This means that it generates 25 happiness net of over-colonization, such that a 2:1 ratio of real systems to temporary/awful systems will net to about no happy impact to overcolonization (while maintaining ecstatic happiness everywhere). Plus, those temporary systems can also use the 5 turns of existence to build 1-2 ships with the Thinkers & Tinkers production.

**Comment by wakystuf** [comment]
Is there maybe a way to at least make this not apply to Riftborn outposts? That would resolve the most egregious of the problems.

**Comment by captaincobbs** [comment]
Yes, that's fairly easy.

**Comment by wakystuf** [comment]
OK, great; I think that would help a lot.

For now I'll label as Needs Documentation and just leave it at the bottom of my list for the wiki.

**Comment by captaincobbs** [comment]
Done

**Comment by wakystuf** [comment]
Documented
