### ISSUE TITLE
Buff Pirates in Lategame

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#360]
Make pirates spawn more / better equipped ships in lategame.
Give pirates better infantry when boosted.

**Comment by Arpharnator** [comment]
yes

**Comment by Arpharnator** [comment]
It is now time I post what modifications have been made to pirates.

So, first, pirates will spawn every 8 turn on fast speed, instead of 10.
Second, rewards from destroying a pirate lair have been greatly increased (list is too long to make one).
Third, pirate infantry troops now have 75% dmg bonus, and 75% health boost. Deployment maximum increased to 1250 per turn. These changes have been made because I wanted to help pirates weak ground invasion at pirate power level 5 and to make sure that you do not have to spend 3 turns orbiting a level 5 lair despite overwhelming troop advantage because pirates can't deploy for shit.
Fourth, pirate lair maximum manpower has been increased, as to make killing them not too easy. The numbers are as follow : 
400 for level 1, 600 for level 2, 800 for level 3, 1100 for level 4, 1500 for level 5. Compare this to 300, 450, 600, 750, 900 for each level respectively.
Fifth, (something you probably don't need to care about), is that pirate lairs generate more manpower.
Finally, only for the endless difficulty of pirates, some new ship loadouts have been introduced that the pirates can use from level 4 and 5. These ship loadouts are much much stronger than the usual ones, usually featuring a complete arsenal of weapons alongside damage enhancers and the like to boost their fleets.
Note that also starting from level 4, pirates will have more than 3 levels of boosting available. The new ships appear at level 4 only if you have sufficiently invested in pirate bonuses, and will naturally appear at level 5, with the possibility of creating a strong fleet if you choose to invest fully in them, featuring around 18 command points of good ships with tremendous combat ability packed in a single one.
The ships themselves can feature weapons that vanilla pirates wouldn't carry, such as bombers, boarding pods, railguns, sieging modules.
Also note that the ships are not generalists and usually carry few different weapon types as to enhance the fleet effectiveness in a single field.  In the same thinking, there are 4 possible fleets for the pirates each of which are more tailored to a certain ship, usually boasting 4 medium ships of either Insectoid/Primitive/Pirate/AdvancedPirate alongside some others for a total 18 command point.


I fully expect some rage from new players playing against these turn 50-60.
Against more experienced players they should be a still relatively easy challenge (I don't wanna have pirates overtaking the galaxy), but you can suffer some losses from them later on.

**Comment by Arpharnator** [comment]
@wakystuf present for u

**Comment by Mermixer** [comment]
> (list is too long to make one).

coward

**Comment by wakystuf** [comment]
@Arpharnator Ooh ooh, what did I win?

**Comment by Arpharnator** [comment]
you gained not having to skim through the code to do the documentation

**Comment by wakystuf** [comment]
Haha, nice. That is actually a very good present; thanks!

**Comment by wakystuf** [comment]
Once it's tagged as "closed" and "finished" then I'll tag it as "Needs Documentation" and then put it on the wiki. I'll probably do a big batch of those sometime later this week

**Comment by wakystuf** [comment]
Is this one done? Should it be closed and tagged as "finished"?

**Comment by captaincobbs** [comment]
As far as I know it isn't merged yet

**Comment by captaincobbs** [comment]
It's still being tested

**Comment by Arpharnator** [comment]
works

**Comment by wakystuf** [comment]
2 questions for you, @Arpharnator:
1) Do pirates automatically get the +75% infantry dmg and health, or only if someone buffs them?
2) Are there any changes to pirate ships below endless pirate difficulty? And within endless, any changes to ships below levels 4-5?

**Comment by Arpharnator** [comment]
1) yes they always have the 75%

2) only within endless 4-5, even tho I think I changed stuff in 3 and the ships you get through paying pirates are slightly stronger design wise
