### ISSUE TITLE
Umbral Choir / Sleeper Buffs

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#387]
These are proposals made by DownToFeed, Mermixer, and Cobbs. The specific numbers will change, but the concepts behind them probably won't.
## Home System Buffs
Replace Collection Bonus 2:
* +x Vision Range per Pop on Main System
* +2x Vision Range per Super Pop on Main System (Shadows)

## Food Penalty Alleviation
Provide Food per Pop on Happy / Ecstatic in Empire
* +5 Food per Pop on Happy
* +8 Food per Pop on Ecstatic
(or just eliminate the food penalty entirely)
What is the function for food required for new pops?
(its like 150 + 3 * (pop+1), 300 + 5 * (pop+1) on normal) 
(Whatever food bonus choir gets should nullify this)
Make Chain Gang absorb all net positive food production

Primary production buffs: allow more improvements to also apply to sanctuaries

## Making Sleepers Useful
(Idea: tie effectiveness of hacks to number of sleepers on a system. Change all hacks to implant at least one sleeper regardless of the option you pick)

+x Science * (shadows +1) per Abducted Sleeper (after taking sleepers via ground invasion or hack)

Add an empire improvement on second and fourth stage to increase number of sleepers taken/planted per hack
Make sleepers harder to remove
Sleepers steal science instead of dust (like 15-30-50 %)
Make sleepers innately generate manpower (1 manpower each)?

# Hacking Program Changes
Make track boost hacking speed on your hacks that pass through
--defensive program placed on friendly nodes

# Potential Hacking outcome changes
Capitol exclusive “Support Revolutionaries” action only applies to systems with sleepers on them
--Hacking Capitol allows you to implant X sleepers on every system
(Maybe make the Government change not actually change the goverment but just fk them for an election or more (maybe fk the political opinion of some/all systems for 10+ turns)

**Comment by wakystuf** [comment]
I just uploaded the change to eliminate the food penalty. Incidentally, that change, in my opinion, also fixes the Sleepers issue, since the incentives are then to pack the home system (as in vanilla), at which point +1% FIDS per sleeper is pretty good.

**Comment by wakystuf** [comment]
A few other thoughts on this:
1) Similar to the sleepers, the production buffs might not be needed now either, since packing pop into the home system will enable them to benefit from various additional production modifiers (AI Labor, T1 generic hero skill, Microwave Pipes, etc).
2) Just out of curiosity, what is the reason to replace the T2 pop collection bonuses? I do like the proposed new ones, but the original ones also seemed mostly fine. Replacing the +5 per Umbral Shadow will also exacerbate food and production issues, however.
3) It seems like the main problem for the UC is that their manpower shortage makes them too fragile, right? So maybe mechanics should be added for them to gain manpower through thematically appropriate means (ex: enable sleepers to steal manpower, give them a little bit of manpower on sanctuaries, maybe a ship module that's like reverse boarding pods by kidnapping manpower from destroyed ships, extra manpower from a pop collection bonus, or make sanctuaries able to siphon manpower from a system if they are colocated, etc). Those are just a few random ideas though.

**Comment by Arpharnator** [comment]
imo manpower should be naturally given by the umbral shadows, it could be cool to have UC be able to scale better with those

**Comment by wakystuf** [comment]
That would be cool. In general, some means for the UC to solve their manpower issues by following their thematic path would be good

**Comment by Arpharnator** [comment]
Made home cooking 3.5% extra food on all systems per pop on HomeSystem (actually it's bestSystem but it doesn't matter since your homesystem will always be the better system)
Added 1 ind to nexus
Added 3 manpower generation to sleepers
Added 6 manpower generation to umbral shadows

**Comment by captaincobbs** [comment]
Add the science per umbral shadow loser

**Comment by Arpharnator** [comment]
ok added 0.1 science per umbral shadow

**Comment by captaincobbs** [comment]
Bad Arphar, no

**Comment by Arpharnator** [comment]
Umbral Shadow pop bonus
Made Umbral Shadow reinforce the scientist opinion instead of pacifist
Umbral shadow pop collection 2 is now 20 FIDS per umbral shadow
Umbral shadow pop collection 3 is now 4 FIDS per Bandwidth (instead of Allocated bandwidth)
Umbral Choir pop collection bonus 2 now gives influence based on Bandwith (instead of Allocated Bandwitdth)

**Comment by wakystuf** [comment]
This sounds good, but the code looks like only 1 influence per Bandwidth for UC pop collection 2?

**Comment by Arpharnator** [comment]
that's baseline, only made it so it's about maximum bandwidth, and not used bandwidth

**Comment by wakystuf** [comment]
Sorry, I don't think I'm following:
Vanilla:  1 Influence per Allocated Bandwidth
Code I saw: 1 Influence per Bandwidth

Are you saying that, combined, they will now get +1 per Unused Bandwidth and +2 per Allocated Bandwidth? I think that's fine if so; I just want to understand for when I later document

**Comment by Arpharnator** [comment]
nono, they get influence equal to their max bandwidth

**Comment by wakystuf** [comment]
Well right, that's what the +1 is, right?

**Comment by Arpharnator** [comment]
+1 influence per max bandwidth

**Comment by wakystuf** [comment]
Right. But your note above said 2! 1 is not the same as 2!

**Comment by Arpharnator** [comment]
>>Umbral Choir pop collection 2 now gives influence based on Bandwith (instead of Allocated Bandwitdth)

the 2 refers to to the pop collection # 
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by wakystuf** [comment]
Oh. Yeah, I need to learn to read; that's my conclusion.

**Comment by Down2Feed** [comment]
UC cant make strategics for shit. The system improvements that increase strategic production only apply to Nexus and not the sanctuaries.
