### ISSUE TITLE
Buffed Riftborn Scrap Kings Law (in Democracy only)

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#404]
I don't think there was an Issue for this one; is it buffing that Scrap Kings law from -20% to -35% cost reduction and from +35% XP to flat +40 XP (only in Democracy) ?

**Comment by Doruk-Coskun** [comment]
The change to Scrap Kings is def not a buff. It increases the industry cost of the ships and in return gives +2 Initial Levels (I updated the UI, we don't use +EXP on UI anymore due to the way the experience system works in the background. You can also notice this if you check out other ship experience improvements.)

**Comment by Doruk-Coskun** [comment]
Scrap Kings was way too powerful and RB was already too good. RB doesn't need ship cost reduction. @wakystuf

**Comment by wakystuf** [comment]
Ah, got it; I see now. I forgot that 0.2 cost reduction is actually a 20% cost increase. I will add that to the wiki

Is there also a change to the law in Republic? It looks like the code I saw in #351 was only for the "normal" version of the law, right?

**Comment by wakystuf** [comment]
@Doruk-Coskun  I think this one is still open

**Comment by captaincobbs** [comment]
There is no Republic variant.
Original: -30% Ship Industry Cost
ESG: +35% Ship Industry Cost, +2 Levels on Ship Creation

**Comment by wakystuf** [comment]
Great; thanks! Documented.
