### ISSUE TITLE
Reworked curiosity spawn probabilities

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#405]

**Comment by Doruk-Coskun** [comment]
Well it is hard to comment on this and hard to document every change but basically what it does is remove Hostile pirate spawn from curios, scales the empire money and science drops so that they are relevant finds, adjusts battle tactics and curiosity system improvement drops. It is not certain to find the most powerful ones so a bit of luck involved etc etc. If you have anything specific to ask go ahead @wakystuf

**Comment by wakystuf** [comment]
Yeah, it looked like it was just a bunch of different stuff, so I'll just document as "Reworked curiosity spawn probabilities" rather than listing every single 1. I was just trying to see if there was some unifying concept that I should include, but sounds like there's not.
