### ISSUE TITLE
Vaulters Rework

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#437]
VALUES WILL CHANGE, THIS IS JUST A PROPOSAL
## Material Expertise:
* Quadrinix changed to +10% Dust and Science per System Level AND Orichalcix changed to +10% Food and Industry per System Level

## Quest Changes
* Buff Quest Weapons
* Buff System Improvements

## Research
* Buff portal research effects to not be garbage
* Research to improve Golden Age research effects
* Change Filter Barges to the following, and made not unique:
  * +1 Base Value on all Strategic Deposits on System Development Level 1
  * +1 Base Value on T1 Strategic Deposits on System Development Level 2
  * +1 Base Value on T2 Strategic Deposits on System Development Level 3
  * +1 Base Value on T3 Strategic Deposits on System Development Level 4

## Senate
* T1 Industrialist Law - Vaulter Unique Version
  * Increased golden age bonus

## Faction Traits
* Change Core World effects to the following (potentially):
  * +10 Happiness while not over the colonization limit
  * % FIDSI Bonus on all systems while under the colonization limit
* New Trait - Unnamed
  * -1 colonization threshold (scales with galaxy size)
  * Increased penalties for going over colonization limit
* Change Involuntary Nomads golden age effects to the following (potentially):
  * +20 Happiness on new System
  * +20 Happiness on all Systems
  * +x FIDSI on new System
  *  No bonuses if you are colonizing?
* Increase Involuntary Nomads Argosy base movement speed

## Defensive Bonuses (new Faction Trait?)
* Give some sort of bonus to Vaulters militarily while fighting in their or allied territory
* Give a military-dependent economic bonus on political party in power? Examples below:
  * +35 Science per CP Destroyed or Lost while in Friendly Territory (Scientists)
  * +20 Manpower per CP Destroyed or Lost while in Friendly Territory (Militarists)
  * +35 Dust per CP Destroyed or Lost while in Friendly Territory (Pacifist)
  * +25 Influence per CP Destroyed or Lost while in Friendly Territory (Religious)
  * +5 Approval per Owned Admiral in Friendly Systems (Ecologists)
  * -25% Repair and Retrofit Dust Cost (Industrialists)

**Comment by captaincobbs** [comment]
@Doruk-Coskun feel free to add anything I missed

**Comment by wakystuf** [comment]
Generally, I agree with most of this. A few thoughts:

* I probably wouldn't nerf Core Worlds with the lower overcolonization level; you'd just be making it harder for them to get resources (particularly to get a diversity of resources on smaller maps with already-low thresholds), mostly. I just generally wouldn't nerf the Vaulters given that they already struggle to compete with the top factions (ex: Cravers, Vodyani). That said, a FIDSI bonus while under the threshold in exchange for a malus while over the threshold seems cool. I just wouldn't lower the threshold.
* The changes to Material Expertise and Involuntary Nomads seem good. Need to do something to enable them to scale, and this will make golden ages good for something other than happiness in the mid/late game.
* The change to Filter Barges also seems fine. That's still a Unique building, right? If it's only 1 per empire then it's hard for it to get abused.

For the law bonuses, I like the idea, but I'd change it up a bit; all of these are "per CP destroyed", as you had:
* Industrialist: bonus strategics (ex: +0.5 titanium and +0.5 hyperium), as they tend to be associated with mining
* Religious: bonus XP (including hero XP), since religious tends to be associated with heroes
* Pacifist: +20 dust (since pacifist factions tend to be mercantile)
* Ecologist: +20 influence
* Ecologist (alternate): + shipment of food sent to nearest system, but may be harder to implement generating a civilian ship like that.
* Militarist: I agree with the manpower, but bonus manpower in a friendly/allied area isn't often that useful (since you get free refills anyway). Maybe give them the manpower AND some % repair/heal?
* Militarist (alternate): Could also give some % chance to steal/recover ships, similar to boarding pods, since the Vaulters are associated with piracy and boarding pods. I think this one is cooler, but maybe harder to implement.
* Scientist: Same as what you have; this one is pretty obvious.

**Comment by captaincobbs** [comment]
> I probably wouldn't nerf Core Worlds with the lower overcolonization level; you'd just be making it harder for them to get resources (particularly to get a diversity of resources on smaller maps with already-low thresholds), mostly. I just generally wouldn't nerf the Vaulters given that they already struggle to compete with the top factions (ex: Cravers, Vodyani). That said, a FIDSI bonus while under the threshold in exchange for a malus while over the threshold seems cool. I just wouldn't lower the threshold.
The idea we had was that they have a low number of really high quality systems. This FIDSI bonus while underneath the threshold would be really substantial, something to make it worth the lowered colonization limit.

> The change to Filter Barges also seems fine. That's still a Unique building, right? If it's only 1 per empire then it's hard for it to get abused.
It is no longer a Unique building, and it's not going to be abusable because the Vaulters consume a high quantity of strategic resources. This, combined with the lowered colonization threshold, means they have to be more picky about what systems they choose to colonize.

> Industrialist: bonus strategics (ex: +0.5 titanium and +0.5 hyperium), as they tend to be associated with mining
I wanted to place more emphasis on obtaining strategics through careful colonization so that their colonization is more meaningful.

> Religious: bonus XP (including hero XP), since religious tends to be associated with heroes
Religious also tend to be associated with Dust, Vaulters already get well equipped ships, I don't want to give them well-leveled ships too.

> Pacifist: +20 dust (since pacifist factions tend to be mercantile)
Influence would be more useful for pacifists, since the only time you ever get a pacifist senate is early game when you have no influence production.

> Ecologist: +20 influence
Ecologists have no association with Influence

> Ecologist (alternate): + shipment of food sent to nearest system, but may be harder to implement generating a civilian ship like that.
Not possible

> Militarist: I agree with the manpower, but bonus manpower in a friendly/allied area isn't often that useful (since you get free refills anyway). Maybe give them the manpower AND some % repair/heal?
Vaulters have terrible manpower production, since they have such massive garrisons. This would give them a way to easily obtain manpower to use in ships.

> Militarist (alternate): Could also give some % chance to steal/recover ships, similar to boarding pods, since the Vaulters are associated with piracy and boarding pods. I think this one is cooler, but maybe harder to implement.
Not possible

**Comment by wakystuf** [comment]
The issue with the overcol reduction is that on smaller galaxy sizes with a default of like 4-5 systems, cutting them below that is just brutal; they might lose access to certain resources altogether. This is particularly true given that they won't be able to tell which systems have T3 strategics until later in the game when they get to T4 of the science tree. Again, they aren't terrible right now, but they aren't great either, so adding a new (potentially significant) handicap is going to make balancing that much tougher.

For the manpower, like I said I'm fine with that, but just make sure it goes into the empire pool, not just onto the ships (which are probably already full in friendly territory). I might still add the healing % as well for militarists though, and then have the industrialists do something else. To me, the free resources aren't abusable as a reliable source of income, since it only applies in friendly territory. In order to benefit from it, someone else has to be feeding you ships. If 0.5 of each is too much, then you could reduce to like 0.25 or something instead.

For ecologists, the +action point is just kind of weird, since ecologists don't have any association with it, and it will be useless like >50% of the time if you are defending. Is it possible to shave cost off of the Argosy for each CP you kill (like 0.25 turns worth of waiting per CP, or something)?

Another alternate one would be happiness (ex: +0.5 per CP destroyed for 5 turns) for the militarists (instead of manpower) and then you could move the manpower over to ecologists, who are associated with food.

**Comment by captaincobbs** [comment]
> The issue with the overcol reduction is that on smaller galaxy sizes with a default of like 4-5 systems, cutting them below that is just brutal; they might lose access to certain resources altogether. This is particularly true given that they won't be able to tell which systems have T3 strategics until later in the game when they get to T4 of the science tree. Again, they aren't terrible right now, but they aren't great either, so adding a new (potentially significant) handicap is going to make balancing that much tougher.
I could pretty easily tie it to galaxy size if needed, I'll probably end up doing that. It's probably not going to be much of a handicap. Finding systems that contain the resources they want it not a problem for them whatsoever, even on small maps. The problem I've generally noticed is that they just don't produce as much as they need to, and overcolonize to compensate for that. Core worlds exists to emphasize the "quality over quantity" economy that the Vaulters were poorly designed around.

> For the manpower, like I said I'm fine with that, but just make sure it goes into the empire pool, not just onto the ships (which are probably already full in friendly territory).

Oops, I misunderstood you then, sorry. The ships are refilled from the empire pool, so I can't really control that. This is specifically to avoid it from going into the system pool. The large system manpower capacity prevents the empire pool from being refilled until you get a good food production.

> I might still add the healing % as well for militarists though, and then have the industrialists do something else. To me, the free resources aren't abusable as a reliable source of income, since it only applies in friendly territory. In order to benefit from it, someone else has to be feeding you ships. If 0.5 of each is too much, then you could reduce to like 0.25 or something instead.

Not making Industrialist produce strategics isn't a balance issue. The reason I chose the +FIDSIM per CP Destroyed/Lost in Friendly Territory is to reinforce the idea of "the Vaulters just adapt to any hardship that they may face, and fighting them in their home territory will just push them harder". I'm trying to make the acquisition of strategics feel more like a scientist mechanic, and contrast their militarist mechanics. The % Heal, while already rare for vaulters, would reinforce the Industrialist theme of tanky ships. The Vaulters already have a variety of unique ways to increase their health, so this would be a more useful wartime bonus than strategics per CP. (Not sure if I'm explaining this well, sorry haha)

> For ecologists, the +action point is just kind of weird, since ecologists don't have any association with it, and it will be useless like

Hmm, the reasoning behind the + action point is because Ecologists have a theme of viciously defending their territory (Unfallen and Nakalim to a lesser extent be a good example). It's a loose connection, but it'd work. Though, as I'm writing this, I had an idea. Why not switch the industrialist and ecologist bonuses? The ships regain hp for ecologists because they're scrapping parts or something, and the industrialists get an action point. I think that'd make more sense than Strategics per CP.

> Another alternate one would be happiness (ex: +0.5 per CP destroyed for 5 turns) for the militarists (instead of manpower) and then you could move the manpower over to ecologists, who are associated with food.
 
I don't think that's possible, I did consider this though.

**Comment by wakystuf** [comment]
The overcol threshold I think is fine if it scales based on map size. They just can't have like 2 out of 4 removed, since that's brutal. If it's scaling from 0-2 based on size (and then get a nice big FIDSI bonus for being under) then I think that would work.

For manpower, it's fine if the ships drain the manpower from the empire pool after the battle. The scenario we'd want to avoid is that the ships already have full (or near-full) manpower at the end of the battle and then the game tries to fill them more, but it can't and therefore the free MP is wasted. If it goes to the empire first, then it will only drain onto the ships if they are running low, in which case none is wasted anyway. TLDR: just make sure it is added to the empire pool, and all is good.

I mostly just find the action point bonus to be thematically quite weird, both in general and in particular for either industrialists or ecologists. It will also usually be useless, because Full Reserves is much more useful for offense (ex: burning a stack of behemoths or low-quality defending fleets) than defense. Here are a few other ideas:
1a) Potential workaround for the happy bonus: Code it as an event that activates for X happy per CP destroyed. Or potentially for a bunch of events, if needed to do a separate event for each CP destroyed. Then each event could be X happy for Y turns (ex: 0.25 happy for 5 turns).
1b) Alternate workaround for the happy bonus: You know that level 1 industrialist colony/happy law? Maybe piggy-back on that architecture to make the game think you've just built a new colony for each CP destroyed (IE, increment whatever the "new colony" variable is by 1 for each CP destroyed), except reduce the happy bonus down a lot, obviously.
If either of those works, then you can give the militarists the happy bonus, and move MP to ecologists.
2) Instead of the extra action point, you could ban retreating (for both sides), similar to a Tractor Beam or ESG Black Hole. Probably would be for militarists, with MP moving to Ecologists.
3) I don't love the extra action point, but if you really want to keep it then maybe do the following:
-Add some extra movement (maybe a full refill, maybe only partial) in addition to the action point, so that they can actually use it to liberate an additional system
-Move the action point +movement to militarists (better fighting) and put MP on ecologists (since it's food-related)

**Comment by wakystuf** [comment]
Oh, and one other idea I forgot: militarists could also just get a % bonus to damage, and/or health and/or shielding in their territory, and then MP moves to ecologists. By definition, that bonus can't be too OP, since you can just choose the number that solves for the equilibrium (ex: if 10% is too much, then what about 5%? 3%? 1%? Or if too little, then 15%?)

**Comment by captaincobbs** [comment]
> For manpower, it's fine if the ships drain the manpower from the empire pool after the battle. The scenario we'd want to avoid is that the ships already have full (or near-full) manpower at the end of the battle and then the game tries to fill them more, but it can't and therefore the free MP is wasted. If it goes to the empire first, then it will only drain onto the ships if they are running low, in which case none is wasted anyway. TLDR: just make sure it is added to the empire pool, and all is good.

That's the plan

> 1a) Potential workaround for the happy bonus: Code it as an event that activates for X happy per CP destroyed. Or potentially for a bunch of events, if needed to do a separate event for each CP destroyed. Then each event could be X happy for Y turns (ex: 0.25 happy for 5 turns).

Not possible

> 1b) Alternate workaround for the happy bonus: You know that level 1 industrialist colony/happy law? Maybe piggy-back on that architecture to make the game think you've just built a new colony for each CP destroyed (IE, increment whatever the "new colony" variable is by 1 for each CP destroyed), except reduce the happy bonus down a lot, obviously.

That sounds even more useless than the action point one then, since you don't generally colonize for long periods of time. I can't just piggy-pack off of it, but it's a neat idea.

> Instead of the extra action point, you could ban retreating (for both sides), similar to a Tractor Beam or ESG Black Hole. Probably would be for militarists, with MP moving to Ecologists.

That was thrown around as a backup idea, and I still like it, but I'd prefer if we replaced the % Health and Action point with an economic bonus of some kind. Raw military bonuses are not really the point.

> 3) I don't love the extra action point, but if you really want to keep it then maybe do the following:
-Add some extra movement (maybe a full refill, maybe only partial) in addition to the action point, so that they can actually use it to liberate an additional system
-Move the action point +movement to militarists (better fighting) and put MP on ecologists (since it's food-related)

First one isn't possible, but second one is a good a good idea.

> Oh, and one other idea I forgot: militarists could also just get a % bonus to damage, and/or health and/or shielding in their territory, and then MP moves to ecologists. By definition, that bonus can't be too OP, since you can just choose the number that solves for the equilibrium (ex: if 10% is too much, then what about 5%? 3%? 1%? Or if too little, then 15%?)

At least with this outline, it was already planned for them to get that kind of bonus regardless of which political party was leading.

**Comment by wakystuf** [comment]
I think that mostly makes sense; 3 points of clarification:
1) Are you saying that it's impossible to refill movement, similar to the En Passant tactic? You could also expand the max and increase the relevant fleet's movement, similar to the Star Boogie Bill, if needed.
2) To clarify for the happiness/colonization concept, I wasn't suggesting tying the law to actual colonization or the Argosy. I just meant that you could find the variable that the law references (ex: $RecentlyColonizedSystems or whatever it's called, and force the game to increment that variable up by 0.1 for each CP killed, or something like that).
3) I think I mentioned this above, but I may have missed the answer (apologies if so): is it possible to shave cost off of the Argosy for each CP you kill (like 0.25 turns worth of waiting per CP, or something)? That would be a great one for the Ecologists if so, since they are tied to expansion/colonization.

**Comment by captaincobbs** [comment]
1. With simulation values yes, the En Passant is a battle action, and I'd be doing this with simulation modifiers and not battle effects.
2. Ahh, I see, I'm not sure how that would work code wise to say whether it's possible or not.
3. As far as I know, not possible

**Comment by Arpharnator** [comment]
@Doruk-Coskun reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by wakystuf** [comment]
OK, the most important parts of this are now done
![image](https://user-images.githubusercontent.com/79942510/119604260-c4e86d00-bdbc-11eb-86d4-ff2456eb1d26.png)
