### ISSUE TITLE
Nakalim Changes

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#455]
Relics do not produce Empire Science directly, and instead each provide a baseline of 10 science to all systems.
Removed -50% science on systems.
Nakalim population changed to be +1 FID and +3 happiness on temple
Cathedral of the lost now gives 5% for each temple, and +5 happiness for each temple as well. Reduced cost as well.
Temples updated tooltip and now gives an extra 5 influence on cold
Sobra gets an exra 5 food
2 new Nakalim only science improvements replacing graviton and evolution foundation, offering science based on your number of relics.

**Comment by NingaublesEyes** [comment]
Cathedral of the lost now gives 5% for each temple, and +5 happiness for each temple as well. Reduced cost as well.

-> ^ 5% science?

**Comment by Mermixer** [comment]
think its fidsi

**Comment by NingaublesEyes** [comment]
NOICE. Looks interesting! Cold gives influence is a nice touch.

**Comment by NingaublesEyes** [comment]
> think its fidsi

That's good! I think it's kind of a fun thing to worry less about the exact mix of planets and just focus on larger systems.

**Comment by Mermixer** [comment]
> I think it's kind of a fun thing to worry less about the exact mix of planets and just focus on larger systems.
smells like vodyani

**Comment by NingaublesEyes** [comment]
Oh I had this odd idea - maybe after you complete their quest chain you could gain a trade subsidy on the Academy planet for your 1st head quarter? Like. You don't really ever ally with them but you can declare war. So I don't know. That's the closest to an alliance / appreciation bonus I can think of. 

Or maybe ... I dunno a free friggen hero.

**Comment by NingaublesEyes** [comment]
> > I think it's kind of a fun thing to worry less about the exact mix of planets and just focus on larger systems.
> > smells like vodyani

So. Smells like unearned victory? Ooooh snap. *flees*

**Comment by NingaublesEyes** [comment]
going to bed ! :D

**Comment by NingaublesEyes** [comment]
Stele Feratory of the Somber Soul - replaces your gravitron

The Nakalem's devotion to religious introspection extends even to their domestication rituals. In order to become a member of the religious orders a Nakalem has to successfully participate in a ritual bonding with one of the unusually silent canines. Bonding to a Lycanine Shoghāl is always a powerful experience. Even the success of the ritual for a new priest may precipitate new miraculous insights in other priests. These predators are assumed by alien dignitaries to be ambush predators due to their silence but in truth Shoghāl are some of the most adaptive predators in the universe.

Foreign dignitaries are often disquieted when they realize just how many canines may accompany even one priest. The disquiet foreign dignitaries feel is viewed by the Nakalem as a reflection of their unquiet souls. To the Nakalem the Shoghāl are believed to be part of the reincarnation cycle of the Nakalem soul. They believed this long before their strange connection to the powerful relics of the Lost was discovered. 

A Nakalem who wishes to join the priests is locked within a structure called the Somber Souls. To build such a structure Steles with Feratories in their base are errected in a maze. Before the priest enters several feral Shoghāl will be released into the structure, one of whom is given a relic. The Shoghāl will immediately disappear into the maze hiding it one of the Steles. Chained to the relic is a key to leave the Somber Souls. In order to survive a Nakalem will require both protection and guide that of a Shoghāl of their own. Sometimes they bring a trained Shoghāl but some insist on the old ways finding their bond among those in the maze. A priest may have to defend himself from ambush or endure a grueling game of cat and mouse until they outlast their pursuers or impress one sufficently creating a unique bond. No experience is the quite the same. 

The closest thing to an ecclescial denomination within the Empire of the Nakalem are those who believe in a fundamental difference of the importance of the Lycanine Shoghāl. While the difference is slight one believes the canines protect and guide the soul of a Nakalem after death and the other believes the canine to be a new Nakalem soul. The canine is so silent and contemplative most priests secretly believe both views to be true. Regardless if it's because they are accompanied by a curious young soul or are bonded to a soul wiser than their own priests tasked with difficult research often gain insight by performing the same ritual of bonding multiple times throughout their lives.

![20210422031200_1](https://user-images.githubusercontent.com/52173864/115726139-50db2500-a337-11eb-90c6-6b598834ac73.jpg)

**Comment by Arpharnator** [comment]
they wrok
