### ISSUE TITLE
tweak governments bonuses

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#466]
1) Dictatorship gets +1 law slot
2) Dictatorship mandatory laws are better:
* Scientists: No change
* Pacifist: 10% building buyout reduction
* Industrialist: +2 Ind per pop
* Religious: +2 infl per pop
* Militarist: +2 MP per pop
* Ecologist: +2 food per pop
3) Federation from 20%-->25% lux cost reduction

**Comment by wakystuf** [comment]
Is this for the effects of republic/federation/democracy/dictatorship? If so, it seems like republic is already fine, federation and democracy are mostly fine, and dictatorship needs some help.

**Comment by Arpharnator** [comment]
yes, it is for that.

**Comment by wakystuf** [comment]
OK. In that case, a few ideas:
* Republic: No change
* Federation: Maybe -33% or -40% lux cost to upgrade instead of -20%? Doesn't need a big buff, I don't think.
* Democracy: May not be doable, but it would be cool to add like -5 pop required for pop collection bonuses, to unlock more of those laws. I feel like that's the real "theme" of democracy: passing a bunch of the laws from the various minor pops in your empire. Democracy also doesn't need a big buff, I don't think.
* Dictatorship: Needs a lot of help
  * Is it possible to have 2 senator slots for heroes (both from the same party)?
  * Is it possible to give them +1 law slot?
  * Probably also worth buffing the non-militarist mandatory laws (and maybe nerfing the militarist one). Currently, it's hard to see why anyone would pick a non-militarist party (aside from ecologist, for only the early-game), vs receiving a free ~200 happiness from Jingoist Joy Bill

**Comment by Mermixer** [comment]
can we change goverment type of uc then btw
they cant get minor laws and thematically they shouldnt be one either
give the dictatorship or something

**Comment by wakystuf** [comment]
That's a fair point. I probably wouldn't make them a dictatorship though; maybe a republic instead? Dictatorship could be weird with ecologist (or militarist)+ sanctuary spam

**Comment by Arpharnator** [comment]
bruh 33-40% federation cost on system dev bruuuuuuuuuuuuuuuh
For democracy that seems kinda useless, it's not like every minor has a law you want and with this many parties you already need so much slots
For Dictatorship I dunno yet I don't really wanna step in autocracy's territorry

**Comment by Arpharnator** [comment]
I think dictatorship is more appropriate for uc because it's a hivemind

**Comment by wakystuf** [comment]
Yeah, maybe give democracy something else small then, idk. Maybe +3 happiness per party represented among active laws? (which would be a max of +12, including Independent)

For federation, what did you have in mind instead? I'm just thinking they need a minor buff to get them up to where Republic is. Maybe -25% system dev? Just throwing out ideas.

Dictatorship has to get a rework in order for this to make sense; it's just so bad in vanilla relative to the others. If you're worried about autocracy, then give that a buff too, I guess. I don't play Cravers, so idk a ton about that.

**Comment by Arpharnator** [comment]
I dunno about democracy cuz I don't really wanna add more to the somewhat lenghty list of effects and it feels bad adding something like bonus approval per different law when you get already so much direct and indirect happiness from being in a democracy.
Federation needs a little something, even tho changing it is a bit awkward cuz you don't wanna add stuff too mcuh powerful, maybe a small bonus or tweak would be fine.

Not sure at all about dictatorship

**Comment by wakystuf** [comment]
I mean I guess you could leave democracy alone, make federation -25% cost, and then for dictatorship add +1 law slot and rework the dictatorship-specific mandatory laws to make them better.

I had assumed the point of this Issue was mostly to fix dictatorship; was there something else you had in mind instead?

**Comment by Arpharnator** [comment]
I wanted to see a bit about governments to see if it was possible to make them more fitting/better

**Comment by wakystuf** [comment]
To close this out, how about I do the following:
1) Dictatorship gets +1 law slot
2) Dictatorship mandatory laws are better:
* Scientists: +2 science per pop
* Pacifist: +2 dust per pop
* Industrialist: +2 Ind per pop
* Religious: +2 infl per pop
* Militarist: +2 MP per pop
* Ecologist: +2 food per pop
3) Federation from 20%-->25% lux cost reduction

**Comment by Arpharnator** [comment]
Don't touch scientist
Add Buyout redution for pacifist instead of an extra buck
Industrialist ok
Religious  ok
Militarist -> nerf the approval given to 20/10 per war with major/minor
Ecologist ok so long you don't delete the +15 approval

Sounds good for fed

**Comment by wakystuf** [comment]
OK, that all sounds good

**Comment by wakystuf** [comment]
OK, this is done, except that ecologist wasn't letting me mess with it (I tried like 5 different ways), so I gave up on that one. The others are all fine

**Comment by captaincobbs** [comment]
There's like 20 versions of the ecologist free law you have to consider

**Comment by wakystuf** [comment]
I could only find the 1; I'm not sure where the others are even located, so that's why I gave up

**Comment by wakystuf** [comment]
Ecologist dictatorship law should now work

**Comment by wakystuf** [comment]
1) Dictatorship gets +1 law slot
2) Dictatorship mandatory laws are better:
* Scientists: No change
* Pacifist: 10% building buyout reduction
* Industrialist: +2 Ind per pop
* Religious: +2 infl per pop
* Militarist: +2 MP per pop
* Ecologist: +2 food per pop
3) Federation from 20%-->25% lux cost reduction
