### ISSUE TITLE
Buff Manpower Luxuries (and fix vanilla manpower bug)

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#481]
I think we should buff Dark Glitter's MP produced per turn to be more in-line with the other FIDSIM luxuries (which are +30 now except for jadonyx). Currently, it generates 10 MP per turn, but drains 200 into the defensive MP of the system. That means that it takes 20 whole turns before Dark Glitter "pays for" itself, and in the meantime your fleets suffer from reduced MP. In the early game fights with 11-14 CPs of attackers/protectors, the 200-600 MP you've drained into defensive MP could really screw your ability to win space battles

**Comment by wakystuf** [comment]
Also fixed hilarious vanilla bug whereby system manpower is multiplied by # of different pop types, since the base value of the manpower pop collection bonus is set to 100% (instead of 0).

Should also buff the other manpower luxuries
* Amianthoid: vanilla effect, plus increase manpower cap by 20 per pop, as well as generating 3 MP per pop
* Virtual Artifacts: vanilla effect, but rework % bonus from 5% per SD to something way higher (maybe 50%?)

**Comment by Arpharnator** [comment]
good catch.
Good effect for Amianthoid, for Virtual Artifacts I think 20% per sd level would work.

**Comment by wakystuf** [comment]
The problem with 20% is that MP production is already only 40% of food, right (and that's if you build Patriot Pills and Exotic Rations for an extra 30%)? In that case, shouldn't it be roughly [Food effect] / 0.4 = 37.5% to provide the same FIDSIM as Mercurite? Then round up to 40%.

**Comment by Arpharnator** [comment]
Manpower produced is 2 times the production of food given to manpower. As such that makes 18.75 but better round it to 20

**Comment by wakystuf** [comment]
Well, that isn't really inherent to the formula though; that is simply an adjustment for GameSpeed. On Normal, it is 1x, so I think we should do 40%

**Comment by Arpharnator** [comment]
that just seems like a lot for no reason other than comparing it to the luxury that is supposed to produce food with no additional side effects compared to a luxury that greatly boosts defensive capabilities

**Comment by wakystuf** [comment]
Well sure, but the side effect (late-game defensive manpower) isn't worth much. A proper invasion fleet will still wipe all the defensive manpower almost immediately anyway.

**Comment by Arpharnator** [comment]
I think you underestimate the value of 100% extra system manpower on the defensive capabilities of a system.
Also remember that sim camp is now readibly accessible to all players, and getting extra ind from manpower is not unnoticeable.

**Comment by wakystuf** [comment]
Oh, I'm already accounting for Sim Camp mentally; that's why this luxury isn't just terrible. Getting an extra 100-200 production is still much, much less good than Endless Foundries, however. 

We also need to account for the "don't screw over fleet MP" problem that we talked about for Dark Glitter. We need to make some assumptions here, but let's take the following scenario:
* Defensive MP of system (pre-Virtual Artifacts): 1000 (if this number is higher, it screws the fleets worse, so I'm erring low)
* Food output of system: 300
* Food to MP % rate: 40% (assumes have built Patriot Pills and Exotic Rations)
* Implied MP Output (40% of 300): 120
* SD level: 3 (for SD4, the numbers will be better, but we need to make sure that Virtual Artifacts are still good for SD3 as well)
* MP % per SD: 20%
* Implied MP % total (3 x 20%): 60%
* Implied MP Output (60% of 120): 72
* Turns until it "pays for" itself (1000/72): 13.9

13.9 is way too long and terrible for fleets. Even 6.9 (from 40%) is not great, but it's at least much more bearable.

**Comment by Arpharnator** [comment]
I think  that unless you did war for 30 turns straight you might not always be in need of manpower and as such can use it freely.
I don't think that kind of luxury is just to "pay for itself" because it makes little sense from the point of view that it expands its own stuff, it's more about providing an advantage.
Also in your calculations, the result you get is for normal speed, and I think 14 turns in normal speed is not that bad, and that 7 turns at fast speed is pretty good.
Also in general systems have 850 manpower with all basic system defense improvements built, and the systems you want to use this kind of stuff on have more like 500-700 food to go with.

**Comment by wakystuf** [comment]
A few things:
* If you "are not in need of MP" then this luxury is potentially worse, since it means it is providing no benefit to your fleets longer-term. Defensive MP is...fine, I guess, but just much less important than fleet MP most of the time. I just don't think we should balance around the assumption that overall MP is effectively not constrained.
* The luxury does need to pay for itself in the sense that it needs to avoid harming your overall military power, which is much more dependent on fleets than on defensive MP.
* I disagree that 14 turns on Normal speed is not that bad, though 7 on Fast is probably fine. Maybe we try to figure out how to make the effect scale with GameSpeed?
* I think for 850 you aren't including +200 from Exotic Rations, right? That should make it 1050. (Without Exotic Rations, the Food to MP % drops to only 30%, which makes the whole thing much worse).
* 500-700 food is a lot for some factions! Horatio and Unfallen probably can spam that, but many cannot. The Lumeris, Sophons, UE, etc might generate that in their capital, but probably not anyplace else. I think we should be balancing around a "typical" faction, and not only around their top 1-2 systems; more like the top ~10 systems or so.

**Comment by Arpharnator** [comment]
The reason I say 500-700 food is because "normal" factions such as UE will never be able to afford the system dev cost of a T3 more than 2 times in a game, and as such will likely focus on their big systems for system dev.
I forgot exotic rations lol.
The main effect of the luxury is for defensive purposes, at which I think it is at least decent at creating stronger ground forces that require more than your typical carrier fleet worth of manpower to bring down in a decent time (before ennemy gets reinforcements).
Ironically the worst thing about this luxury is that having more manpower results in longer battles, and as such an increased probability of seeing your stuff destroyed despite winning.
(If I'm not mistaken, having troops help fight against the invasion reduces the likelihood of your stuff getting destroyed, because I think that the % chance of destruction of defending troups reduces the chance of destruction)

**Comment by wakystuf** [comment]
With properly optimized trade (especially with the modest lux output buffs), I think normal factions can still afford several system devs. Not a ton of them, but probably at least 5-10. Lumeris will have way more, but have no real food advantages.

Fundamentally, pure defense...mostly sucks. At least compared to +X% FIDSI per SD. So I'm trying to buff it enough that the secondary effects of a) overall empire MP and b) Sim Camps bonus are worthwhile enough to make them relevant as compared to ProtoSpores, Endless Foundries, etc. Even at 40% MP/SD I'd probably still rather use ProtoSpores or Endless Foundries, in most situations.
