### ISSUE TITLE
Balancing - 1.4 Testing

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#571]
1) Revert golden age FIDS to vanilla,
2) Remove overcol cap increase techs, replace with golden age buffs?
3) Maybe cut filter barges in half? Or maybe leave it alone and let the overcol changes maybe do their thing (Dont Touch Filter Barges Effects)
4) -15% FIDSI per overcol
5) -1 more overcol vs what we have now (so -2 on "Large" size, scaling to -1 for smaller and -3 for really big)
6) Golden age happy to +10/10 and make ind special law for +10 during golden age
7) Replace AA with something cool that doesn't give colonization cap

**Comment by wakystuf** [comment]
Put propaganda tied to a crappy empire tech in T3

**Comment by wakystuf** [comment]
13) Fix Unfallen vineship cost back to vanilla base cost (right? Maybe I missed something on that)

**Comment by wakystuf** [comment]
Completed:
* Revert golden age FIDS to vanilla,
* Confirmed that Filter Barges work the same way as Miner's Union
* -15% FIDSI per overcol
* -1 more overcol for Vaulters vs what we have now (so -2 on "Large" size, scaling to -1 for smaller and -3 for really big)
* Golden age happy to +10/10

Still to-do:
* Remove Vaulter overcol cap increase techs, replace with golden age buffs?
* Increase duration to free colonize
* Increase the cost for early colonization

* Replace Vaulter AA with something cool that doesn't give colonization cap
* Make ind special law for +10 during golden age
* Remove Vaulter-specific effect on T3 sci law
* Put propaganda tied to a crappy empire tech in T3
* Adjust Filter Barges and/or resource pop collection bonus (to discuss further)

**Comment by wakystuf** [comment]
Additional items from the Discord chats earlier today:
* Hissho damage booster module locked to 1 per ship to prevent stacking
* Some building that reduces ship building cost (maybe a Hissho thing? Idk what it was)
* Increasing law passage costs for later laws (I can look into this one; I already know exactly how to do it, I just need to think about the numbers)
* Vaulter scout 1 support slot converted into a non-support slot
* Vaulter colonization cost to be reduced to vanilla (but leave the longer-time to become free)

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/120431738-93097480-c381-11eb-9b2e-dbca0d316b29.png)
This is listed wrongly, it should have been listed as Approval

**Comment by wakystuf** [comment]
@Doruk-Coskun I already listed that in bugs (separate) issue and (I think) fixed it in the latest pull request

**Comment by Doruk-Coskun** [comment]
Adding Ghost Crew trait to UC.
Ghost Crew: -80% bases manpower cap on ships. 95% resistance to boarding pod damage and weapon crew kill.

**Comment by Doruk-Coskun** [comment]
Initial Vodyani changes:
1. pop bonus to be +3 and +6 boosted
2. increase scaling of ark costs
3. increase starting dust

**Comment by captaincobbs** [comment]
> Adding Ghost Crew trait to UC.
> Ghost Crew: -80% bases manpower cap on ships. 95% resistance to boarding pod damage and weapon crew kill.

Make sure to remove the old ship manpower trait

**Comment by Doruk-Coskun** [comment]
> Completed:
> 
> * Revert golden age FIDS to vanilla,
> * Confirmed that Filter Barges work the same way as Miner's Union
> * -15% FIDSI per overcol
> * -1 more overcol for Vaulters vs what we have now (so -2 on "Large" size, scaling to -1 for smaller and -3 for really big)
> * Golden age happy to +10/10
> * Increase duration to free colonize
> * Increase the cost for early colonization
> * Remove Vaulter overcol cap increase techs, replace with golden age buffs
> * Remove Vaulter-specific effect on T3 sci law
> 
> Still to-do:
> 
> * Put propaganda tied to a crappy empire tech in T3
> 
> Not happening:
> 
> * Replace Vaulter AA with something cool that doesn't give colonization cap
> * Adjust Filter Barges and/or resource pop collection bonus (unless someone disagrees)
> * Make ind special law for +10 during golden age (too much work and maybe impossible, unless somebody else wants to do it)

![image](https://user-images.githubusercontent.com/25507419/120471935-ff9a6880-c3ad-11eb-904c-26c9629899ae.png)
Is this supposed to be -15%? @wakystuf

**Comment by wakystuf** [comment]
Cobbs wanted to do -10% per overcol; that was his change. I'd probably leave it at -15% but I also don't care very much either way.

**Comment by wakystuf** [comment]
@captaincobbs @Doruk-Coskun Pulling all the to-do's into one place:

WAK
* Increasing law passage costs for later laws

Cobbs:
* Put propaganda tied to a crappy empire tech in T3

Chaos:
* Hissho damage booster module locked to 1 per ship to prevent stacking
* Some building that reduces ship building cost (maybe a Hissho thing? Idk what it was)
* Adding Ghost Crew trait to UC (and removing the other related trait)

**Comment by Doruk-Coskun** [comment]
Lumeris colonies will get +10 food per turn instead of food shipment
First tier deeds requirement and droplist will be updated

**Comment by Doruk-Coskun** [comment]
Starting explorer and colonizer of every faction except Horatio has been refitted to fill every module. Vodyani ark also starts with a full refit.

**Comment by Doruk-Coskun** [comment]
Every faction except Lumeris starts with 100 Dust. Lumeris starts with 300 dust.

**Comment by Doruk-Coskun** [comment]
Bomber and figher damages against ship types will be rechecked. Every battle tactic will be adjusted so that 100% of fighters attack the enemy ships rather than protect the fleet against bombers.

**Comment by Doruk-Coskun** [comment]
Discuss changing mines of UC to give +1 strat on all sancturies

**Comment by Doruk-Coskun** [comment]
Slightly change curio droplist probabilities to distinguish different types of curios from each other.

**Comment by Doruk-Coskun** [comment]
Wrath of Tonatsi, hissho quest beam damage buffed.

![image](https://user-images.githubusercontent.com/25507419/120655954-d9e39100-c48b-11eb-982e-4777a34a5aaf.png)

**Comment by Doruk-Coskun** [comment]
Hissho Unique ship cost reduction building effect nerfed to be reasonable

![image](https://user-images.githubusercontent.com/25507419/120661592-18c81580-c491-11eb-87d3-1bf51d718978.png)

**Comment by Doruk-Coskun** [comment]
Vodyani law upkeep cost increased 100%
![image](https://user-images.githubusercontent.com/25507419/120673927-48c8e600-c49c-11eb-9b52-cc1e1a0a9c93.png)

**Comment by Doruk-Coskun** [comment]
Half the time it takes for a system to rebel due to low approval

**Comment by Doruk-Coskun** [comment]
Vodyani pop stats reduced 4 -> 3 FIDS and 8 -> 6 FIDS boosted

![image](https://user-images.githubusercontent.com/25507419/120677317-9eeb5880-c49f-11eb-8d9c-2b9b8e434acc.png)

**Comment by Mermixer** [comment]
> Half the time it takes for a system to rebel due to low approval

as statet in balance senate, this is a non-issue as long as supress is still a thing

**Comment by wakystuf** [comment]
Listing everything in one place to keep us organized

Completed:
* Revert golden age FIDS to vanilla,
* Confirmed that Filter Barges work the same way as Miner's Union
* -10% FIDSI per overcol
* Golden age happy to +10/10
* Increase duration to free colonize
* Increase the cost for early colonization
* Remove Vaulter overcol cap increase techs, replace with golden age buffs
* Remove Vaulter-specific effect on T3 sci law
* Increase cost of T3 leeching modules
* Vody base pop reduced to +3/6
* +100% law upkeep on vody
* Reworked Hissho Red Blade assembly (lower ship cost % reduction and T2 strats from 25 of each to 15 of each)
* Wrath of Tonatsi, hissho quest beam damage buffed
* Slightly change curio droplist probabilities to distinguish different types of curios from each other. Ruins for curio modules, Signal for minor pops, Atmospheric for dust/science/influence and battle tactics. This doesn't mean it is guaranteed to drop them but it has a higher chance to drop these kinds of rewards.
* Every faction except Lumeris starts with 100 Dust. Lumeris starts with 300 dust.
* Bomber and figher damages against ship types will be rechecked. Every battle tactic will be adjusted so that 100% of fighters attack the enemy ships rather than protect the fleet against bombers.
* Starting explorer and colonizer of every faction has been refitted to fill every module. Vodyani ark also starts with a full refit (Beams, 2x hull plating, 2x essence and 2x science)
* Vodyani explorer starts with beams, UE starts with missiles, cravers start with a slug and one laser, RB starts with lasers, Sophons start with a beam
* First tier deeds requirement and droplist will be updated: Stage 2 deeds requirements are increased (10 -> 16 curio search, 100 ->125 dust on a system, 8 -> 10 planets colonized, 4 -> 5 systems on the same constellation) Rewards of these stage 2 deeds are adjusted to be 2000 dust or 75 Titanium or 75 Hyperium
* Hissho damage booster module locked to 1 per ship to prevent stacking

Still to-do:
* Put propaganda tied to a crappy empire tech in T3
* Half time required to trigger rebellion (I agree with Merm this is mostly pointless, but I'm fine if somebody wants to code it anyway)
* Lumeris colonies will get +10 food per turn instead of food shipment
* Adding Ghost Crew trait to UC (and removing the other related trait)
* Increasing law passage costs for later laws

Not happening:
* Replace Vaulter AA with something cool that doesn't give colonization cap
* Adjust Filter Barges and/or resource pop collection bonus (unless someone disagrees)
* Make ind special law for +10 during golden age (too much work and maybe impossible, unless somebody else wants to do it)

**Comment by Doruk-Coskun** [comment]
1- Reduce Science Cost reduction of Behemoth Science module
2- Remove Scout Spam hero level up

**Comment by wakystuf** [comment]
@Doruk-Coskun I added your comment into the list above, with 1 of them already taken care of

**Comment by Doruk-Coskun** [comment]
Stellar Analytics behemoth module science on special node increased 40 -> 50 and science cost reduction reduced 1  -> 0%
Stellar Node Study behemoth module science on special node increased 80 -> 100 and science cost reduction reduced 2  -> 1%
Stellar Node Study 2 behemoth module science on special node increased 160 -> 200 and science cost reduction reduced 3  -> 2%

**Comment by Doruk-Coskun** [comment]
Advanced node analyzer, strategic on special node effect increased 1 -> 1.5 strategic on special node
![image](https://user-images.githubusercontent.com/25507419/120749449-4d79b280-c50d-11eb-9ec4-ce3e321548e8.png)

**Comment by Doruk-Coskun** [comment]
Start lumeris with buyout tech and 15% buyout cost reduction. For Lumeris add 10% buyout cost reduction to Multi Thread Management. For Lumeris Reduce Impactless sites buyout cost reduction to 15%. This means lumeris in total can get 50% buyout cost reduction scaling with the game.

**Comment by Doruk-Coskun** [comment]
Buff gnashast battle ground tactic

**Comment by captaincobbs** [comment]
Lowered lumeris outpost action cost to 25 + 25 * (System Count - 1)

**Comment by Doruk-Coskun** [comment]
Ministery of Truth strategic reduced to 80 -> 50 green/purle. Effect reworked to be 5 FIDSI and 10 Approval per War on every system. Industry cost reduced on fast to 6120
![image](https://user-images.githubusercontent.com/25507419/120885774-46c56b00-c5f3-11eb-8e4e-188fafa95074.png)

**Comment by Doruk-Coskun** [comment]
Empire Dev quadrant tier 5 deed rewards buffed to be 5 -> 15 dust per science building and 5 -> 15 influence per science building

**Comment by Doruk-Coskun** [comment]
(DONE) Prudent positions weapon damage reduction effect reduced 35 -> 25%

**Comment by Doruk-Coskun** [comment]
Improved Flotilla Shield (Orange Flotilla shield) module moved to Anti Matter Channeling Tech and removed from curiosities.
Delayed H Repair Bots module module moved to Science Tech Quadrant Stage unlock 3 and removed from curiosities.

Flotilla shield module shield amounts have been 50% increased across the board.

**Comment by Doruk-Coskun** [comment]
(DONE) Buffed Flak efficiency against squadrons from 6.5% to 9%

**Comment by Doruk-Coskun** [comment]
Ghost Crew empire improvement needs priority added to it so that it doesn't effect the troop modules added afterwards

**Comment by wakystuf** [comment]
A few things:
1) Is that buff to flak efficiency big enough? How much flak is now required to match up with each bomber module?
2) The Lumeris are basically starting with 25% reduction, since they start with buyout tech, right?
3) I might give Lumeris another 5% buyout reduction somewhere so that they can get to 75% cap with superspuds instead of getting to the weird total of 70% instead
4) Maybe we start the Lumeris with even more dust at first so that they can actually use the buyout? 300 is basically just enough for an outpost and some retrofits

**Comment by Doruk-Coskun** [comment]
1- We will test and see tbh
2- I doubt that's how it is. I still need to see how cobbs did it but I believe lumeris has access to buyout and the buyout tech and if lumeris researches the buyout tech instead if the buyout it gets additional 10% reduction
3- nah
4- nah

**Comment by wakystuf** [comment]
Listing everything in one place to keep us organized

Completed:
* Revert golden age FIDS to vanilla
* Confirmed that Filter Barges work the same way as Miner's Union
* -10% FIDSI per overcol
* Golden age happy to +10/10
* Increase duration to free colonize
* Increase the cost for early colonization
* Remove Vaulter overcol cap increase techs, replace with golden age buffs
* Remove Vaulter-specific effect on T3 sci law
* Increase cost of T3 leeching module
* Vody base pop reduced to +3/6
* +100% law upkeep on vody
* Reworked Hissho Red Blade assembly (lower ship cost % reduction and T2 strats from 25 of each to 15 of each)
* Wrath of Tonatsi, hissho quest beam damage buffed
* Slightly change curio droplist probabilities to distinguish different types of curios from each other. Ruins for curio modules, Signal for minor pops, Atmospheric for dust/science/influence and battle tactics. This doesn't mean it is guaranteed to drop them but it has a higher chance to drop these kinds of rewards.
* Every faction except Lumeris starts with 100 Dust. Lumeris starts with 300 dust.
* Starting explorer and colonizer of every faction has been refitted to fill every module. Vodyani ark also starts with a full refit (Beams, 2x hull plating, 2x essence and 2x science)
* Vodyani explorer starts with beams, UE starts with missiles, cravers start with a slug and one laser, RB starts with lasers, Sophons start with a beam
* First tier deeds requirement and droplist will be updated: Stage 2 deeds requirements are increased (10 -> 16 curio search, 100 ->125 dust on a system, 8 -> 10 planets colonized, 4 -> 5 systems on the same constellation) Rewards of these stage 2 deeds are adjusted to be 2000 dust or 75 Titanium or 75 Hyperium
* Hissho damage booster module locked to 1 per ship to prevent stacking
* Remove Scout Spam hero level up exploit.
* Adding Ghost Crew trait to UC (and removing the other related trait)
* Reduce Science Cost reduction of Behemoth Science module, increase science per module to compensate.
  * Stellar Analytics behemoth module science on special node increased 40 -> 50 and science cost reduction reduced 1 -> 0%
  * Stellar Node Study behemoth module science on special node increased 80 -> 100 and science cost reduction reduced 2 -> 1%
  * Stellar Node Study 2 behemoth module science on special node increased 160 -> 200 and science cost reduction reduced 3 -> 2%
* Advanced node analyzer, strategic on special node effect increased 1 -> 1.5 strategic on special node
* Lumeris colonies will get +10 food per turn instead of food shipment
* Nerf UE Quest reward science building, on anomaly 5 -> 3 science per pop
* Rewrite Vodyani Ark module cost formula: Empire essence stock cap is scaled by 400-700-1100-1600-2200 (Starts with 400, first increment by 300. Increment is increased by 100 for each new ark) Ark cost is 100 less essence than the empire cap
* Prudent positions weapon damage reduction effect reduced 35 -> 25%
* Prudent Positions removed from tech tree and added to curiosity discovery.
* Instead of Prudent Positions, Temporal Drag has been added to the same place in the tech tree and removed from curiosities.
*  Buffed Flak efficiency against squadrons from 6.5% to 9%
* Improved Flotilla Shield (Orange Flotilla shield) module moved to Anti Matter Channeling Tech and removed from curiosities.
* Delayed H Repair Bots module module moved to Science Tech Quadrant Stage unlock 3 and removed from curiosities.
* Flotilla shield module shield amounts have been 50% increased across the board.
* Ministry of Truth strategic reduced to 80 -> 50 green/purle. Effect reworked to be 5 FIDSI and 10 Approval per War on every system. Industry cost reduced on fast to 6120
* Lowered lumeris outpost action cost to 25 + 25 * (System Count - 1)
* Buffed gnashast battle ground tactic:
  * Health bonus to defending troops increased 30 -> 40%
  * Damage dealt to attackers increased to 1000 minimum and 1500 maximum
* Start lumeris with buyout and 15% buyout cost reduction.
  * For Lumeris add 10% buyout cost reduction to Multi Thread Management.
  * For Lumeris Reduce Impactless sites buyout cost reduction to 15%.
  * For Lumeris Xeno NLP remains at 10% buyout cost reduction.
  * This means lumeris in total can get 50% buyout cost reduction scaling with the game.

Still to-do:
* Put propaganda tied to a crappy empire tech in T3
* Bomber and figher damages against ship types will be rechecked. Every battle tactic will be adjusted so that 100% of fighters attack the enemy ships rather than protect the fleet against bombers.
* Half time required to trigger rebellion (I agree with Merm this is mostly pointless, but I'm fine if somebody wants to code it anyway)
* Increasing law passage costs for later laws
* Increase industry cost of higher tier modules to compensate for the removed base ship costs increase with military tech stage unlocks.
* Ghost Crew empire improvement needs priority added to it so that it doesn't effect the troop modules added afterwards

Not happening:
* Replace Vaulter AA with something cool that doesn't give colonization cap
* Adjust Filter Barges and/or resource pop collection bonus (unless someone disagrees)
* Make ind special law for +10 during golden age (too much work and maybe impossible, unless somebody else wants to do it)
