### ISSUE TITLE
Umbral Choir + Hacking Changes

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#606]
I've talked to SimpletonAnt, he had the following suggestions to make Umbral and Hacking better:

- Make piggyback give a hacking speed boost based off of the number of hacking programs on an enemy node (potentially also some ground battle malus)
- Sleepers are incredibly easy to remove, making it more expensive to remove them would be ideal
- Their economy is much worse than it was before, he suggests giving their quest some economic rewards that affect sanctuaries
- Give movement after combat regardless of battle tactics?
- They need something to increase their combat capabilities, they're both too fragile and too weak to do much militarily

**Comment by Mermixer** [comment]
> Their economy is much worse than it was before, he suggests giving their quest some economic rewards that affect sanctuaries
huh, really now... well i dont mind the eco boost, so i guess

> Give movement after combat regardless of battle tactics?
im smelling a cancer mechanic right there, though obv it loses to enemy just spamclicking after delaying combat to get their actual fleet there

> They need something to increase their combat capabilities, they're both too fragile and too weak to do much militarily
true

**Comment by wakystuf** [comment]
Piggyback should be mostly fine already. Need to be careful not to increase speed in the way described here, since it will accelerate hacking of capitals most of all, and that could enable them to directly win through Supremacy. I would leave that part alone.

Making sleepers harder to remove is fair, though again need to be careful not to make Supremacy too easy. I would suggest either a) increasing the costs (ex: happy penalty) for removing them, but not changing their efficacy/speed, or b) making it work the same as vanilla on Home systems and only apply changes to other systems

I'm skeptical that the eco buffs or movement are necessary, but the military piece maybe? Idk. They should have strong production generally to be able to pump out a lot of ships, and strats should be OK given they don't have to spend very much on buildings + they get lots from curiosities.

**Comment by captaincobbs** [comment]
I think the general consensus from the discussion this morning (for me) was that they needed to be buffed militarily but that Chaos is stubborn.

**Comment by wakystuf** [comment]
That's the piece I'm most uncertain of. I generally think Eco does NOT need a boost, and sleepers DO need a boost, but combat I'm unsure. What exactly is the problem now that we fixed their fleet MP situation? I continue to feel pretttty sure that there's a way to really abuse evasion for them that should make them competitive in space, unless I'm missing something.

**Comment by wakystuf** [comment]
To help alleviate the concerns about the UC dying too easily (since I don't really think their fleets need a buff if they are able to properly exploit Evasion), I'd propose the following:
1) Greatly reduce the cost of home translocation to make it an actually usable mechanic (the -50% BW in vanilla is totally crippling). Maybe -10% or -20% for 5T (3 on Fast) would be more suitable.
2) Less critical, but could also reduce charge time required for beacons to 10T (5T on Fast)

Another option is to add traits, quest rewards and/or buildings which dramatically increase defensive ground troop effectiveness (health and/or dmg), damage to attackers, etc

**Comment by Doruk-Coskun** [comment]
Guys, no. No no no. We are not doing anything to UC. We already provided proof that UC lacks nothing to the balance senate with mermixer. If you want further proof I will play multiplayer with UC and show how good they are. Dont make any changes without consulting me please or I will get slightly mad.
