### ISSUE TITLE
Merge with Idrinth's Academy Rework

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#61]
Only merged the Academy Aggression stuff

**Comment by wakystuf** [comment]
I pulled the description of this mod; do all of these sound correct? I don't have Awakening, so it's harder for me to check.
- Isander's initial stress is reduced, so he won't start in late game mode when there are 12 Nakalim players
- Lower Stress Fleets are smaller, so early game won't have carrier's to handle
- There's no manpower on master fleets, so no one gets a free invasion
- All Roles have been buffed to be brought on roughly the same level
- Role preferences have been adjusted, so that not everyone goes for the admiral
- The Academy doesn't colonize

**Comment by wakystuf** [comment]
Oh, and also, how does the lack of manpower on the fleets interact with boarding pods? Probably worth clarifying that as well.

**Comment by captaincobbs** [comment]
Point 3 is incorrect, we greatly lowered the carry capacity for the academy ships so they are terrible for evasion, and gave ships highly roughly stage 3 gear. This gives them a weakness to kinetic weapons + shields.

I can give you specific on point 4 if you care.

It means that they are more easily captured with boarding pods, yes.

**Comment by wakystuf** [comment]
OK, great; thanks.

For point #4, just from looking through the code it seems that you added the following?
- Librarian: +100% hacking speed, can research technologies 1 tier above what is unlocked (similar to Scientist mandatory law) [assuming my interpretation is correct, does this stack with the scientist law?]\
- Master of Dust: -2 cost to trade agreements (I had thought these were separately reworked to cost flat 50 influence, however, so I'm not sure what this would do. Does it generate 2 influence per pop?)
- Vault Keeper: +10% influence radius (similar to that new minor faction trait)
- Admiral: +5% damage on weapons modules

**Comment by captaincobbs** [comment]
Master of Dust has some code shenanigans going on, both parties involved with the agreement get free trade deals. Proposal, Upkeep, and Cancellation. Also, the academy generates more dust.

Admiral gets +5% damage on all ships per military era.

I forgot to mention, point #5 needs more elaboration. All factions have a set "role order" based on the strengths of their faction, aka, they all choose their role based off of their faction needs. UC will tend to go for spear, Vaulters will tend to go for vault keeper, etc.

**Comment by wakystuf** [comment]
OK, got it. So does the Librarian bonus stack with the Scientist law?

I'm not sure I totally understand the "role order" concept you mentioned (maybe just because I don't know much about Awakening in general). Is the idea that different factions must accomplish different goals in order to earn the roles?

**Comment by captaincobbs** [comment]
Yes it stacks, you can research up to 2 eras ahead, not that that is much use.

I'll show you what I mean, role order wise.

**Comment by wakystuf** [comment]
Great. I think this one is all set.
