### ISSUE TITLE
Make the Craver Population Bonus interesting by adding a Law Unlock

### ISSUE THREAD

**Issue by ThanosDeGraf** [captaincobbs/ESG-Mod#614]
Have it be something like a self destruction protocol. 
+X Depletion Points per turn on Planet
+Y FIDS per Planet
+Z FIDS per Population

Idea being that the FIDS Bonus and Depletion Points on Planets is so overwhelming, that there is basically a 50% Chance of the Cravers eating themselves to death, but also a 50% Chance of eating the rest of the galaxy. Also, because it is a Law, it is optional to the player and for them to decide. Meanwhile other changes to their Capstone Collection Bonus can still be made.

**Comment by wakystuf** [comment]
Copy-pasting from my Discord post:
2 thoughts: 
1) they definitely don't need a net buff, depending on whether you were thinking of this as incremental or not
2) I don't think we want depletion from laws. Depletion must be manipulated at the planet level in order to work, so applying some empire-wide is probably not great design. We thought about that as part of the law rework and decided not to

Unless someone objects, I will plan to close this in a day or so
