### ISSUE TITLE
Lumeris buf, trade comps yeild science equal to dust

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#683]
Title, Lumeris get science on their trade comp equal to their dust value.

Maybe even consider a trait for improved freighters

**Comment by Arpharnator** [comment]
Also I will put into that trade a 500% increase from trading comp food and ind (should still be not that high)

**Comment by wakystuf** [comment]
I can probably help with this eventually, since I know where most of this stuff lives from dealing with the trade rework in 1.4.

* For science, equal is a lot, but this generally seems like probably a good idea? Maybe start with like half or something?
* Yeah the trade bonuses to food and ind are total shit. Probably should greatly buff them for everybody, tbh and then buff the Lumeris ones even more. 
* I tried to improve freighters a bit already; I just didn't want to go too crazy since trade can kind of scale exponentially. If you want to give them a little more love then that could be fine, as long as we're careful to make sure it doesn't go boom

**Comment by Arpharnator** [comment]
I'm already done, and I don't  think I wanna touch the freighters actually

**Comment by Arpharnator** [comment]
Last lumeris skill changed to be 500% extra food and ind from trade comps
Trait given to them making them get 500% extra food and ind from trade routes, as well as a much higher multiplier on science from trade routes.
The +500% are not crazy but just a decent/low amount, but still a million times more than 0.6 food lul
